### ISSUE TITLE
プロジェクトのタイトルとサブタイトルを考える

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#101]
## タイトル

Meister Hackers

## サブタイトル

高橋さん預かり

## いろいろ修正

高橋さん預かり

* Heroku
* GitHub
* Slack

**Comment by takahashi19** [comment]
・Free code Camp
・

**Comment by tsu-nera** [comment]
お願いします！！

**Comment by dh-megane** [comment]
「開発者：Developer」「交わる・マッチング：Match」「OSS活動で」という言葉の組み合わせで
**DevelopMatcher For OSS** はどうでしょうか？
（読み方は、ディベロップマッチャー・フォー・オーエスエス）
かなり造語感があるので、@LeonardoMatusaki のレビューが怖いかも。

**Comment by tsu-nera** [comment]
Matcherはエンジニア的には、テスティングフレームワークの用語（テストの評価条件を定義するメソッド）なので違和感があります。
Developは動詞なところも違和感があります。

とはいえ、いい代案は思いつきません・・・ :bowing_man:

**Comment by tsu-nera** [comment]
DevMeetsとかは？？ DevOps的な。

**Comment by dh-megane** [comment]
語呂は良い感じがします！

**Comment by tsu-nera** [comment]
## Team Meister

チームラボみたいな。

Meisterはドイツ語です。Masterの意味。

ニュルンベルクのマイスタージンガーからアイデアを得ました。

[ニュルンベルクのマイスタージンガー \| オペラディーヴァ](https://opera-diva.com/meistersinger/)

ニュルンベルクのマイスタージンガーの中軸になっているのは、中世のマイスター制度の一つの行事である歌合戦です。中世は現代のように国家資格などが無い時代。金細工や、靴屋、歌手に至るさまざまな技術は、現在の組合にあたる組織が、技術を伝承するための仕組みを作っていたんですね。

それがマイスター制度です。

駆け出しの頃から徐々に位があがり、各業界の最高位にはマイスターと呼ばれる称号がついたと言います。マイスタージンガーのジンガーは歌い手という意味。今のような音楽大学などない時代ですから、歌手も技術を学ばないとちゃんとした歌は歌えなかったわけです。

**Comment by tsu-nera** [comment]
https://youtu.be/pNdLpJILRzs

ついでに、こちらも聞きましょう。ニュルンベルクのマイスタージンガーの序曲は、ナチスドイツの大会で国民を洗脳するためにつかわれました。

**Comment by tsu-nera** [comment]
## Meister Hackers

**Comment by LeonardoMatusaki** [comment]
## CooperatOSS
　cooperate(協力する) + OSSの造語
　読み方：コオポレイトス

## CompanyOSS
　company(仲間) + OSSの造語
　読み方：カンパニオス？

**Comment by dh-megane** [comment]
CollabOss

**Comment by tsu-nera** [comment]
https://github.com/WEBsinjyuku/github-open-products/issues/101#issuecomment-464610748

決定

**Comment by tsu-nera** [comment]
* heroku
* github
* slack

**Comment by tsu-nera** [comment]
サブタイトルは高橋さん預かり

**Comment by tsu-nera** [comment]
テーマカラーは緑がいい

**Comment by tsu-nera** [comment]
[![Screenshot from Gyazo](https://gyazo.com/b8603f51655311b2d0876e7c2ce555fb/raw)](https://gyazo.com/b8603f51655311b2d0876e7c2ce555fb)

**Comment by takahashi19** [comment]
>* Heroku
>* GitHub
>* Slack

このSlackって僕らのSlackですか？それともこのアプリ用のSlack（オンラインサロン用等）ですか？

**Comment by takahashi19** [comment]
Slack以外は変更完了しましたー！

**Comment by tsu-nera** [comment]
ありがとうございます。 リポジトリ名は、meister-hackersがいいです。理由は、大文字が慣例的につかわれていません。slackは、ぼくらのとオンラインサロン両方でお願いします。

**Comment by tsu-nera** [comment]
わたしのほうで変更しました

**Comment by tsu-nera** [comment]
決まったので閉じます
