### ISSUE TITLE
今必要な人材。もしくは候補者

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#110]
人材候補随時
①バックエンド：Rails実務歴1年程度で2時間程度ジョインできる人材
②デザイン/フロントエンドSEO/アナリティクス/に興味を持っている人材

採用方法
・各メンバーが随時もくもく会などに参加した際にチームに入れるか検討する。

メンバー募集前にみてもらいたい条件（↓下記コメント参照）

**Comment by takahashi19** [comment]
<h2>募集概要</h2>
<p>現在4人でのチームを組んで開発中。バックエンド４名（実務経験者の方と自分（未経験）GitHubのオープンソースで作る予定なので就活用に制作物を作りたい方、個人アプリの作成をチームでやってみたい方を募集</p>
<h2>開発概要</h2>
　　<font size="2">”GitHubで開発したい人と開発に協力したい人をマッチングすることを目的とするWebサービスを開発をします"</font>

<h2>対象者：以下のいずれか一つに当てはまる方</h2>
<font size="2">
　・プログラミングの職業訓練校/専門/民間のスクールに在学/卒業している。<br>
　・Twitterクローン等の簡易アプリ開発経験がある。<br>
　・ProgateのRuby/Railsをすべてやったことがある。<br>
　・Railsチュートリアルを一度やった事がある。<br>
</font>
<h2>参加条件</h2>
<font size="2">
　　・①GitHubと②Railsの開発に興味がある事<br>
　　・毎週2回の打ち合わせに参加できる人（水曜日と休日）<br>
　　・チーム開発に協力的な方（教え合ったりする事ができる方）<br>
　　・3月1日までjoinが可能な方<br>
</font>
<h2>この開発を通じて得られるモノ</h2>
<font size="2">
　　・就活用/実績用の制作物<br>
　　・GitHubを用いたチーム開発の経験<br>
　　・Ruby on Railsの開発経験<br>
　　・チーム開発者同士の技術交換<br>
</font>
<h2>開発環境（技術選定）</h2>
<font size="2">
<h4><strong>　バックエンド</strong></h4>
　　・Ruby 2.6<br>
　　・Rails 5.2.2<br>
<h4><strong>　フロントエンド</strong></h4>
　　・Slim<br>
　　・Vue.js<br>
　　・Bulma<br>
<h4><strong>　DB</strong></h4>
　　・PostgreSQL<br>
<h4><strong>　インフラ</strong></h4>
　　・Heroku<br>
<h4><strong>　開発環境</strong></h4>
　　・Slack<br>
　　・GitHub<br>
　　・Google Apps<br>
<h4><strong>　連携サービス</strong></h4>
　　・CirCleCI<br>
　　・Sider<br>
<h4><strong>　その他</strong></h4>
　　・工期：６週間（予定）
</font>

<h2>活動拠点</h2>
<p>
渋谷または新宿</p>

**Comment by takahashi19** [comment]
## 候補者（takahashi19）
・LT大会であった方、Rails歴1ヶ月

**Comment by dh-megane** [comment]
@takahashi19 
募集概要を読みました。

> ### 参加条件
> ・①GitHubと②Railsの開発に興味がある事
> ・毎週2回の打ち合わせに参加できる人（水曜日と休日）
> ・チーム開発に協力的な方（教え合ったりする事ができる方）
> ・3月1日までjoinが可能な方


下記程度にゆるくしたほうが良いかもと思いました。
・①GitHubと②Railsの開発に興味がある事
・水曜日か休日のどちらかのオフライン会議（作業）に参加できること
・チーム開発に協力的な方（教え合ったりする事ができる方）
・３月１日以降も継続して参加を検討できる人

> ・水曜日か休日のどちらかのオフライン作業に参加できること

これは単純に週２回の打ち合わせの両方に参加して頂くのはハードルが高い感じがしました。

> ・３月１日以降も継続して参加を検討できる人

こちらは「3月1日までjoinが可能な方」だと便利屋さん（短期間で良いから労働力を提供してくれ！）
 という感じを受けました。

採用方法については「もくもく会などで声をかける」という方法で良いと思いますし、
自分も協力します！

**Comment by tsu-nera** [comment]
こちら、wikiにも転載したいです。理由は、勧誘のときのページとして共有したいからです。

https://github.com/WEBsinjyuku/github-open-products/issues/110#issuecomment-462233423

**Comment by tsu-nera** [comment]
うーん、高橋さん、Markdown記法は今後必ず必須となるスキルなので、覚えたほうがいいとおもいますね〜〜〜 🤔

**Comment by tsu-nera** [comment]
[メンバー募集要項](https://github.com/WEBsinjyuku/github-open-products/wiki/%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E5%8B%9F%E9%9B%86%E8%A6%81%E9%A0%85)

Markdownに変換してwikiに変換しました。

**Comment by takahashi19** [comment]
3月1日のLT会でVue.jsをやりたいエンジニアを募集します。うまくいけば3月3日日曜日に合流。

【機能】
・ダッシュボード機能
・チャット機能
【どのくらいの方を求めてるか】（以下のいずれか）
・Vue学習歴は1ヶ月程度以上
・猫本「基礎から学ぶVue.js」などを学習している, 
・v-for, v-ifを使ったことがある人
・実際のWebアプリでVue.jsを使ってみたい人
【人数】
2人くらい
【その他】
週１〜2回一緒に勉強できる人
他技術などの説明に関しては[メンバー募集要項](https://github.com/WEBsinjyuku/github-open-products/wiki/%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E5%8B%9F%E9%9B%86%E8%A6%81%E9%A0%85)を参照
