### ISSUE TITLE
Rollbar導入

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#115]

**Comment by tsu-nera** [comment]
オーナーの高橋さんではないとインストールできませんでしたので、よろしくお願いします。
わからなければ、もくもく会で一緒にやりましょう。

https://elements.heroku.com/addons/rollbar

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/6db3dbf38eaeefbcf6427d6e0c199755/raw)](https://gyazo.com/6db3dbf38eaeefbcf6427d6e0c199755)

**Comment by tsu-nera** [comment]
@takahashi19 
https://rollbar.com/github-open-products/meister-hackers/settings/collaborators/

みんなのメアドを入力してアクセス権限をあたえてくれますか？

**Comment by tsu-nera** [comment]
連携が完了しました。
