### ISSUE TITLE
【プロジェクト掲示板機能】削除・募集終了機能

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#116]
## 機能設計

* 募集終了、削除をサポートする。

### 募集終了

* 募集終了の場合は、個別表示ページのタイトルの下に、**募集は終了しました** と表示する。
* 募集終了の場合は、一覧表示ページのタイトルの横に、**募集終了** と表示する。
* 募集中と募集終了の状態をDBに記録する。
* 合わせて募集開始、募集終了の日付をDBに記録する。
* 募集終了から募集中へ戻す機能をサポートする。
* 募集終了、募集中の設定は、編集画面から操作する。時間が来たら募集終了に変更するようなことはしない。

### 削除

* 削除は、個別ページの編集の横にポタンを設置する。
* 削除ボタンを押すと、**本当に削除しますか** というダイアログを表示して削除する。

**Comment by tsu-nera** [comment]
非公開 or 未公開はどうする？プレビューとかも。

**Comment by tsu-nera** [comment]
設計をします。

**Comment by dh-megane** [comment]
> * 合わせて募集開始、募集終了の日付をDBに記録する。
> * 募集終了、募集中の設定は、編集画面から操作する。時間が来たら募集終了に変更するようなことはしない。

募集開始、募集終了の日付を持たせる理由とは何ですか？
前に喫茶店で会話した際は、フラグで制御ということだっだので編集画面で募集終了的な項目に
☑️入れるだけだったと思います。
「募集終了、募集中の〜しない。」の記載があるので「開始日未到来や募集終了日以降は表示しない」
という制御のためではないのだと思いますが、上記2項目の使用用途を教えて下さい。

**Comment by tsu-nera** [comment]
> 募集開始、募集終了の日付を持たせる理由とは何ですか？

created_at, updated_at的なタイムスタンプです。検索やソートでつかうかもしれないからです。
募集終了はフラグ制御のつもりです。

**Comment by dh-megane** [comment]
承知しました。
3月1日のv1.0では使用しないけど、機能改修に備えた項目ということですね。
自分は設計して頂いた仕様で問題ありません。

**Comment by takahashi19** [comment]
対面でお話聞きましたー！

**Comment by tsu-nera** [comment]
この機能はレオさん待ち。
個別表示ができたら着手。

**Comment by tsu-nera** [comment]
3/1までに必須ではない。
