### ISSUE TITLE
宣伝用ランディングページ(トップページ）

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#117]
## 7. 製品仕様の視覚化

プレスリリース・LPの元ネタとなる。いよいよサービス設計！

**Meister Hackers - エンジニアのためのマイスターコミュニティ**

### はじめに

中世ヨーロッパのマイスター制度にインスパイヤされています。マイスター制度は大学などの教育機関や資格がない時代における技術伝承の仕組みです。駆け出しの頃から徐々に位があがり、各業界の最高位にはマイスターと呼ばれる称号がついたといいます。

会社が教育に対して投資をせず、現場の即戦力が求められる近年の採用情勢を鑑みると、エンジニアは会社には依存せずに学び成長する必要があります。そのためには、エンジニアにも師弟関係なるものが必要です。

そこで、現在のエンジニア業界において、このマイスター制度なるコミュニティを復活させて、ベテランエンジニアが中堅、駆け出しエンジニアを育てる仕組みを作ります。

### 特徴

* 仲間をみつけて開発チームを結成
* 師匠となるべきベテランプログラマとの出会い
* GitHubつかったオープンソース開発
* オフラインMeetUpとの連携
* オンラインSlack コミュニティとの連携

### 機能

* 開発メンバー募集掲示板機能
* 開発メンバースカウト機能（予定）
* GitHubダッシュボード機能(予定)

### 利益

* 駆け出しエンジニアは無料でベテランエンジニアからのフィードバックを得られます
* ベテランエンジニアは無料でオープンソース開発のコントリビューションを得られます
* 実務レベルのチーム開発を経験することができます
* 保守開発では得られない、要件定義からデプロイまでの 0->1開発を経験することができます
* オープンソース開発に貢献でき、エンジニアとしての地位が向上します
* 良質なポートフォリオや開発メンバからのリコメンドを得て、就活や転職で有利になります

**Comment by takahashi19** [comment]
https://runteq.jp/
こんな感じで作っていきたい。カラムは３つ〜４つのもの。プレゼンでサービス固め次第作成を並行して行く予定

**Comment by takahashi19** [comment]
これは3月1日までですよね？

**Comment by tsu-nera** [comment]
いや

**Comment by tsu-nera** [comment]
担当をわたしかから高橋さんに。高橋さんが知り合いのデザイナさんにお願いするよう。

**Comment by takahashi19** [comment]
サービスの完成次第やっていきたいです。3月9日あればとても良い

**Comment by tsu-nera** [comment]
3/10までにレビューする時間がない。レビューしないと外に出せないので3/10はなしで。

**Comment by takahashi19** [comment]
文章 @tsu-nera 
デザイン @LeonardoMatusaki

**Comment by tsu-nera** [comment]
## 1

[![Screenshot from Gyazo](https://gyazo.com/713cf4d7a6fc747f7a833709d8174da1/raw)](https://gyazo.com/713cf4d7a6fc747f7a833709d8174da1)

会社を越えてつながり
共に創り、共に教え合い、共に成長する

オープンソースで結ばれた本物の仲間と出会う
エンジニアのためのマイスターコミュニティ

## 2

[![Screenshot from Gyazo](https://gyazo.com/b935bdce10c3cbd583b30aadf62d6483/raw)](https://gyazo.com/b935bdce10c3cbd583b30aadf62d6483)

時は中世ヨーロッパ...大学や教育機関がない時代。
駆け出しの職人はギルドに所属し、腕を磨き、マイスターと呼ばれる最高位の職人を目指し、切磋琢磨した。

そして現代の日本...会社が教育に対して投資をせず、現場の即戦力が求められる時代。
駆け出しエンジニアは、会社に依存せず学び成長する必要がある。

今こそ、エンジニアの師弟関係が必要だ。
そこで、現代のエンジニア業界においてマイスター制度を復活させ、
ベテランエンジニアが中堅、駆け出しエンジニアを育てる仕組みをつくりたい。

## 3

[![Screenshot from Gyazo](https://gyazo.com/b935bdce10c3cbd583b30aadf62d6483/raw)](https://gyazo.com/b935bdce10c3cbd583b30aadf62d6483)

チームを結成し、０から１を

開発メンバー募集掲示板でチームメンバを集めよう！

保守開発では得られない、要件定義からデプロイまでのゼロイチ開発を体験し、
スキルを高めながら良質なポートフォリオを作成できます。

もし、あなたが駆け出しエンジニアなら、
ベテランエンジニアからのフィードバックを無料で得られます。

もし、あなたがベテランエンジニチアなら、
オープンソース開発のコントリビューションを無料で得られます。

オープンソースに貢献することでエンジニアとしての地位が向上し、
就活や転職で有利になります。

## 4

５つの特徴

仲間をみつけて開発チームを結成
師匠となるべきベテランプログラマとの出会い
GitHubつかったオープンソース開発
オフラインMeetUpとの連携
オンラインSlack コミュニティとの連携

## 5

さあ、仲間と共に圧倒的成長をしよう！

**Comment by takahashi19** [comment]
LGTM
Meister Hackersの趣旨と筋があっていて気持ちも伝わるいい文章だと思います。

**Comment by tsu-nera** [comment]
あ、こちらは、打ち合わせでの対面レビューを考えています。

**Comment by dh-megane** [comment]
自分もオッケーだと思いました。
詳しくは対面レビューで。

**Comment by takahashi19** [comment]
LPを置く場所
→view/posts/top
ログインの仕様
・未ログインでも閲覧可能にする

**Comment by tsu-nera** [comment]
下書き
