### ISSUE TITLE
マイページの表示・編集機能

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#119]
## 設計

個別表示(show)、編集(edit)を用意する。新規作成、一覧表示、削除は用意しない。

### 表示内容

他にもあれば追記をお願いします。

* ニックネーム (github)
* 画像(github)
* 都道府県
* 性別
* twitter
* github
* blog
* facebook
* 自由タグ(所属とか、会社、学校とか）
* 自己紹介文[自由記述]

## イメージ

詳細は実装者に任せますので、ラフに。

### 個別表示

* 議論のポイントは、１カラムにするか、２カラムにするか。
* 編集ボタンはどのあたりに配置するのがよいか？

[![Screenshot from Gyazo](https://gyazo.com/37daee1078e4fe6ab8aa289d9c396739/raw)](https://gyazo.com/37daee1078e4fe6ab8aa289d9c396739)

### 編集

* 初期値は空白。
* 値なしでDBに保存することを形容する。

[![Screenshot from Gyazo](https://gyazo.com/09f53e12c356c660ca2650ed41d17bad/raw)](https://gyazo.com/09f53e12c356c660ca2650ed41d17bad)

**Comment by tsu-nera** [comment]
設計をします。

**Comment by tsu-nera** [comment]
レビューおねがいします。

**Comment by tsu-nera** [comment]
年齢は隠したいひともいるので、削除

**Comment by tsu-nera** [comment]
編集は、自由紹介文の下にボタンを押す。

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/48f0d3262a2a36c98e9b44b09e10afc7/raw)](https://gyazo.com/48f0d3262a2a36c98e9b44b09e10afc7)
SNSのボタンイメージ

**Comment by takahashi19** [comment]
マイページの表示・編集機能
これって開発用に表示(show)と編集(edit)はissue分けますか？

**Comment by tsu-nera** [comment]
PRわけますので、issueはわけません。

**Comment by takahashi19** [comment]
とりあえず作ってみました
[![Screenshot from Gyazo](https://gyazo.com/c8c5a452ccb8051bacad244fd7307999/raw)](https://gyazo.com/c8c5a452ccb8051bacad244fd7307999)

**Comment by tsu-nera** [comment]
打ち合わせで高橋さんは発表用スライド作成をするため、わたしが引き継ぐことになりました。手が空いたひとに手伝ってもらう。
