### ISSUE TITLE
Slackでのオンラインコミュニティ作成

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#139]
アイデア、ご意見お待ちいています。

**Comment by tsu-nera** [comment]
## 類似コミュニティ

* [運営者ギルド \- 運営者ギルド外部向けScrapbox](https://scrapbox.io/admin-guild-pr/%E9%81%8B%E5%96%B6%E8%80%85%E3%82%AE%E3%83%AB%E3%83%89)
* [【入江開発室】世界を変えるWEBサービスをつくる人たちの秘密基地。 \- CAMPFIRE \(キャンプファイヤー\)](https://camp-fire.jp/projects/view/74574)

**Comment by tsu-nera** [comment]
[日経発。チームメイクアプリ SOLMU（ソルム）](https://pr.nikkei.com/solmu/)

**Comment by takahashi19** [comment]
>* [運営者ギルド - 運営者ギルド外部向けScrapbox](https://scrapbox.io/admin-guild-pr/%E9%81%8B%E5%96%B6%E8%80%85%E3%82%AE%E3%83%AB%E3%83%89)

ここスラック のアクティブユーザーがとても多いですね。仕組みがすごく良くて真似して行きたいです

**Comment by takahashi19** [comment]
Slackを作成します。
仕様は* 運営者ギルド - 運営者ギルド外部向けScrapbox
アクティブが多く真似たい

**Comment by takahashi19** [comment]
[Slackのワークスペース作成。](https://join.slack.com/t/meister-hackers/shared_invite/enQtNTU3NTk0NTgxNDI0LTU1YjJlMDA0ZDkyODQ4YjI5NGMxMmVjYmY5MDdjYTRhOTFjMmEyNzBhMzI1ZGFkOGVlMDk1ZmI4MWU2ZGU5ODE)
後でオーナー権限を与えてみなさんも編集できるようにしますー

**Comment by takahashi19** [comment]
作ったので終了。
運営についてはまた相談
