### ISSUE TITLE
このプロダクトのサービスサイド再検討

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#145]
少しふわったとしたので、プレゼン資料作成のため再度考案します。

**Comment by takahashi19** [comment]
【アンケート】
①チーム開発の募集は全員が開発者であったほうが良いか（マーケやりたい、営業、SEOやりたい、マネジメントやりたいという人についてはどう思うか）

②発起人がエンジニアではない場合は参加したいと思うか。

③自分より未熟なレベルだけのエンジニアだと入ろうと思うか。

④このプロジェクトが終わった後、このアプリがどんな形なら自身が本当に使うと思うか。

**Comment by LeonardoMatusaki** [comment]
【アンケート回答：松崎レオナルド】
①開発者であったほうがいいと思う
　➡︎エンジニア以外の人（営業等）が入ることが嫌ということは決してないけど、エンジニア以外の人がプロジェクトを立てることによって、ただ単にエンジニアをコスト0で動かそうと考える輩がでてくることが凄く懸念されるから（ランサーズみたいにエンジニアの安売りになるようなことをしたくないかな）

②思わない

③サービスが面白そうなら思う

④このサービスでオープンにみんなで協力してポートフォリオを作れることが理想。

**Comment by hiromoto-kazuya** [comment]
【アンケート】
①チーム開発の募集は全員が開発者であったほうが良いか（マーケやりたい、営業、SEOやりたい、マネジメントやりたいという人についてはどう思うか）
### 全員が開発者であった方が良い
理想としては全職種選べる方が良いと思う(サービスとして成立させたいとなったらエンジニアリング以外の力も必要なため)。
けどOSS開発という切り口から作られた当サービス(meister hackers)であれば、ユーザーはエンジニアのみで構成されていた方が明瞭かつ、開発もしていきやすいのではと感じるため。

②発起人がエンジニアではない場合は参加したいと思うか。
### アイデアと構成メンバー次第

③チームに自分より未熟なレベルのエンジニアだけであった場合入ろうと思うか。
### 思わない
チーム開発がしたいというマインドの裏には知識や技術を交換/学習したいという思いがあるので。

④このプロジェクトが終わった後、このアプリがどんな形なら自身が本当に使うと思うか。
　・発起人側で使うか
→ 発起人は私は使う予定はないです。笑
　・応募側で使うか
→ サービス構想 or メンバーのレベル感が明瞭であると応募する可能性は高まる、不明瞭な要素が多いと参加しづらい。難易度たかそうですが、例えばgithub情報からユーザーの言語レベルを見いだせるみたいな仕組み(forkwellのサービスにそんなのありましたよね。)があると、応募で使いたくなる。

**Comment by dh-megane** [comment]
【アンケート回答：dh-megane】
①チーム開発の目的が「サービス立ち上げ」か「コミュニティ作成（同じ技術に興味ある人を
　集めたい、チーム開発の経験を積みたい）」で変わると思いますが、基本的に開発者で
　構成されていた方が良いかなと思います。
　
　営業・マーケ：LTまでに早く完成させろ！
　開発者：技術習得が目的だし、普段の仕事があるからコミットは低くしたかった...。
　　　　　手を動かしてないのによく言うよー...。

　上記みたいなモメたり／ギクシャクしそうで大変そうな気がします。
　それぞれの立場を理解すること・意識合わせが難しそうです。　

②思わないです。発起人が開発サイドにも積極的に協力・参加してくれるようなタイプであれば
　すごく良いですが、そういう人はいないのかなという印象です。
　タダ働きしてくれる人を集めるのに悪用されそうなイメージ。
　
③会社などの組織・集団で後輩指導はすることは多いので、あまり思わないかも。
　プライペートでもということになると、けっこう疲れそう。
　個人で仕事しており、純粋にチーム開発をしたいというときは頑張れるかも...。

④発起人側／応募側の両方で使用したいと思います。
　やりたいことが自らアドバイスできる・Giveできるテーマの場合であれば発起人で活動します。
　この知識を習得したいとき・スキル不安があるときは応募する感じです。
