### ISSUE TITLE
サインアップボタンがウィンドウ幅によっては見えない

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#159]

**Comment by takahashi19** [comment]
それは把握してますーGitHubのログイン自体は作りましたが
まだnavbarのデザインやフロントエンド部分は終わってないので #96 をcloseしてません。
今後レスポンシブにする事もログイン時に名前出すかも開発する予定です。今週の日曜日あたりにやろうかと思ってます

**Comment by tsu-nera** [comment]
issue #96にも詳細を書いてもらってもいいでしょうか？

**Comment by takahashi19** [comment]
バグのラベルとissueってことは早急に対処した方がいいですか？何か他の開発に影響あるという事でしたら今日中に取り急ぎ仮でレスポンシブにします。

navbarに他の情報を載せる必要なく今のナビバーの形でレスポンシブ（サインインとログアウトのみ）の内容で完成ならそれですぐに作りますよー。記載情報によってはハンバガーバーにするか迷ってたので。

**Comment by tsu-nera** [comment]
いや、急ぎではないです。
小さな不具合を発見したら、遠慮せずにバグラベルをつけてどんどん上げてほしいです。
そうしないと、見逃しますし、予選中に見つかると予選敗退になりますので。

**Comment by takahashi19** [comment]
了解ですありがとうございますー

navbarは全体に影響を与える仕様だと思いますので今日中に仕様検討のissueをあげます。

**Comment by takahashi19** [comment]
解消したので閉じます
