### ISSUE TITLE
Heroku ReviewApp設定

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#165]
Heroku Ownerしかできないようなので、よろしくお願いします。

[Heroku Review AppsでPRごとに動作環境を作成せよ \- Qiita](https://qiita.com/kon_yu/items/6d2c0ae91d0176ceb167)

**Comment by takahashi19** [comment]
テストはしてないのですがこれで動くと思いますー
[![Screenshot from Gyazo](https://gyazo.com/fc8de41e549ec6791fcd819838f54bbe/raw)](https://gyazo.com/fc8de41e549ec6791fcd819838f54bbe)

[![Screenshot from Gyazo](https://gyazo.com/01a8df4201b2822dd553e27dd717633e/raw)](https://gyazo.com/01a8df4201b2822dd553e27dd717633e)

**Comment by tsu-nera** [comment]
動きました。閉じます。
