### ISSUE TITLE
デザイン再適用(slim→Vue.js)

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#170]
デザイン下記
https://www.figma.com/file/EIj8A4jV7ksxwESWRKYuiKrR/Untitled?node-id=0%3A1

仕様は
@tsu-nera さんの方式：Vue.jsとRailsをAPI方式で繋ぐ
期限：4月中旬くらいまで（コードレビューがなく、保守性のため）

それぞれの割り当て
- [x]  Navigation Before Login (_navbar.html.slim)→@takahashi19
- [x]  Navigation After Login (_navbar.html.slim)→@takahashi19
- [x]  Footer (_footer.html.slim)→ @takahashi19 
- [x]  Show All View (index.html.slim)→ @dh-megane 
- [x]  Show Post View (show.html.slim, )→ @LeonardoMatusaki　@takahashi19 
- [x]  Show Post View（MessageBoard.vue）→　@hiromoto-kazuya 
- [x]  Show Post View with Button (show.html.slim, _form.html.slim)→ @hiromoto-kazuya  
- [x]  User Show View (MyPage.vue)→  @dh-megane 
- [x]  Edit User Show View (MyPageForm.vue)→　@shikky0331 
- [ ] 宣伝用ランディングページ(トップページ） #117→

タスク分け

機能改善・障害一覧
・#281 ガチ募集、ゆる募集 →未実装
・#170 デザイン再適用(Vue.js移行)→半分完了
・#274 MyPageForm キャンセルボタン押下時にFlashメッセージ表示される→
・#273 投稿画面 content 初期表示時にテンプレート表示→未完了
・#272 【ロゴ作成】navbar&favicon→完了
・#267 参加ボタン押下時処理（応募者／起案者の連絡手段)→完了
・#265 GitHubリポジトリURLチェック処理 @shikky0331 仕掛中→完了
・#263 未ログイン時のコメント投稿制限→完了
・#258 プロジェクト一覧画面 Mustashe{{}}が見える→未完了
・#244 ユーザ編集がログアウト中も可能である。→完了
・#199 入力フォームの文字数制限の設定→未完了
・#174 Markdown対応/募集記事に画像埋込→未完了
・#117 ランディングページ作成→未完了
・#86  GitHubAPI 並列実行(index)→？
高橋追記
・#279 404・503ページの作成（デザイン有り）→半分完了

**Comment by tsu-nera** [comment]
3/3にやる

**Comment by dh-megane** [comment]
@LeonardoMatusaki が作業完了
対象画面は以下の通り。担当者割当は、 @takahashi19 にお願いする。

- [ ]  Navigation Before Login (_navbar.html.slim)
- [ ]  Navigation After Login (_navbar.html.slim)
- [ ]  Footer (_footer.html.slim)
- [ ]  Show All View (index.html.slim)
- [ ]  Show Post View (show.html.slim, MessageBoard.vue)
- [ ]  Show Post View with Button (show.html.slim, _form.html.slim)
- [ ]  User Show View (MyPage.vue)
- [ ]  Edit User Show View (MyPageForm.vue)

**Comment by takahashi19** [comment]
3月9日まで→でslim使いたい方はslimでVue.js使いたい人はVue.js
3月10日〜→全てをVue.jsに変更

**Comment by dh-megane** [comment]
デザインメモ（Slackだと流れてしまうため)

- Show All View (index.html.slim)

  - [ ]  １行に２明細（ブラウザ幅が変われば、１明細にする？　＊レスポンシブ）
  - [ ]  募集中、募集終了の表示位置、イメージを確認する

- Show Post View (show.html.slim, MessageBoard.vue)

  - [ ]  募集は終了しましたの表示位置、イメージを確認する
  - [ ]  コメント削除は3/9は対応しない

- _form.html.slim

  - [ ]  募集区分（がち、ゆるめ）は3/9は対応しない

- User Show View (MyPage.vue)

  - [ ]  アカウント削除機能は実装しない予定なので、対象外でよい。
  - [ ]  登録日の行は不要。
  - [ ]  未設定の場合は見出しのみ表示するか（行そのものを出力しないか？）
  - [ ]  登録していない連携サービスのアイコンは表示しない

- Edit User Show View (MyPageForm.vue)

  - [ ]  登録日の行は不要。
  - [ ]  性別はラジオボタン。

**Comment by takahashi19** [comment]
追記です。
宣伝用ランディングページ(トップページ） #117 
ここも出来れば間に合わせたい・・・

**Comment by takahashi19** [comment]
Vue.js木曜日以降にデザイン当てる

**Comment by dh-megane** [comment]
デザインで質問ですが、bodyのwidth上限を1440pxに指定する理由は
何でしょうか？？
```
body {
  background-color: #f9fbfe;
  max-width: 1440px !important;
}
```

右端の背景色が白く描画されるのが気になるので、100%に変更したいと思うのですが...
相談させて下さい。
【今のレイアウト：右端の背景色は白】
![2019-03-07 6 53 10](https://user-images.githubusercontent.com/40923242/53916601-d93dd380-40a5-11e9-94f1-57acc09ff79f.png)

【提案レイアウト：body widthを100%にする】右端の背景色も設定される！
```
body {
  background-color: #f9fbfe;
  max-width: 100% !important;
}
```
![2019-03-07 6 55 50](https://user-images.githubusercontent.com/40923242/53916687-228e2300-40a6-11e9-8beb-d81a1abf55d4.png)

**Comment by takahashi19** [comment]
LP別にあるので
