### ISSUE TITLE
User.create時にgithu  iconをDBに保存

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#173]

**Comment by hiromoto-kazuya** [comment]
## 仕様イメージ
- やりたいこと
githubのアカウント画像URLをuserテーブルに保存する。

- 手順
1. userテーブルに`avater_url`カラムを追加。
2. user.rb内`find_for_github_oauth`メソッドで、auth情報からgithubのアカウント画像URLを取得し、`avater_url`に保存。
