### ISSUE TITLE
Markdown対応/募集記事に画像埋め込み

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#174]
markdownが作成可能になればそのまま募集記事内に画像を埋め込み可能。

**Comment by tsu-nera** [comment]
3/1まで必須というわけではないのでちょっと優先度落とす。

**Comment by takahashi19** [comment]
アクションテキストを入れてマークダウン不対応のため一旦棚上げ

Vue.jsにviewが変更されるためその場合はmarkdownで対応可能になるかも→要調査

**Comment by dh-megane** [comment]
挑戦するのは有りかなと思います。
今出ている機能改善の一覧を作成して、着手可能か優先順位を確認しましょう。
機能改善の一覧は自分のほうで作成します。

**Comment by takahashi19** [comment]
・マークダウンの締切。
　・29日の夜。30日締切
　・マークダウンをヒロモトさん確認。
　　→無理なら改行のみどうするか検討
　　　→それも無理な場合はmarkdownを入れない。

**Comment by tsu-nera** [comment]
Markdownは保留になったはず。閉じる。
