### ISSUE TITLE
チャット機能　バックエンド

### ISSUE THREAD

**Issue by shikky0331** [WEBsinjyuku/meister-hackers#193]
https://github.com/shikky0331/flux_tutorial_try
https://github.com/Progate/flux_tutorial

**Comment by tsu-nera** [comment]
## しきさんのタスク

https://github.com/shikky0331/flux_tutorial_try/tree/master/app/controllers/api

* controllers/api 配下の５つのファイルを controllers/chat に移動してください。
* APIが正しく機能するか確認してください。

**Comment by shikky0331** [comment]
・ドキュメントを書いたことがないのですが、どのような感じで書けばよろしいでしょうか？
・chatのメッセージは新しくtableを作る感じでしょうか？
・userのAPIは正しく機能できてます。

**Comment by dh-megane** [comment]
https://github.com/WEBsinjyuku/meister-hackers/wiki/Func-Spec_index
https://github.com/WEBsinjyuku/meister-hackers/issues/71

上記2つを参考にドキュメントは書ければ良いのかな？と思います。
どんな機能があるのか、APIの活用方法など書ければ良いと思いますよ。

**Comment by shikky0331** [comment]
ありがとうございます！
参考にして書いてみます！！

**Comment by tsu-nera** [comment]
> ドキュメントを書いたことがないのですが、どのような感じで書けばよろしいでしょうか？

API仕様書がほしいです。

理想はこんな感じ（自動生成)
https://app.swaggerhub.com/apis/tsu-nera/auto-matching/1.0.0

とりあえず、

GET /api/users/xxxx

request:
-xxx
-xxx

response:
-xxx
-xxx

な感じで、箇条書きにしてください。

> chatのメッセージは新しくtableを作る感じでしょうか？

はい

**Comment by shikky0331** [comment]
API仕様書作りました。初めてなので不足・修正箇所ありましたら指摘して頂けると助かります！
https://shikky0331.github.io/index.html

**Comment by tsu-nera** [comment]
ありがとうございます、ものすごくよいです。これがほしかったです。

たぶん、https://shikky0331.github.io のドメインは変えたほうがいいです。
これは、githubユーザアカウントに対して一つしか割り当てられないので。
