### ISSUE TITLE
チャット機能（とりまとめ）

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#195]
## See below

#194 
#193 

## Purpose

Demodayに向けた目玉機能のひとつとして、チャット機能を開発します。これは、しきさんがProgate研修でつかった、Rails/Reactアーキの実装のVue.jsへのポーティングとなります 。

## 機能仕様

* １対１のチャットルームを作成する。
* 個別投稿の参加するを押すと、依頼者と参加者の１対１のチャットルームができる。
* チャットルームは別ウィンドウで開く。閉じると終了する。
* チャットルームの仕様は、プロゲート研修に従う。
* チャット一覧ページを新規作成する。
* チャット一覧ページには、チャットやりとり中のルームの一覧が並ぶ。

## 検討

* Slackとの連携を考えると面白いのだが、排他をどうするか？

## 参考

* https://github.com/shikky0331/flux_tutorial_try
* https://github.com/Progate/flux_tutorial

**Comment by tsu-nera** [comment]
MVCにかわる、Fluxアーキはとても勉強になるため、レビューは全員でおねがいします。

**Comment by takahashi19** [comment]
#194 フロントエンド
#193 バックエンド

作るときに復活お願いします
