### ISSUE TITLE
本番環境でのデータ投入

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#196]
## 目的

DEMODAYにむけて、運用している感を出すために登録数を増やす

## 候補

* th https://github.com/WEBsinjyuku/meister-hackers
* tsu-nera https://github.com/peach-hack/auto-matching
* tsu-nera https://github.com/tsu-nera/bakuchi
* tsu-nera https://github.com/tsu-nera/self-revolution

**Comment by tsu-nera** [comment]
優先度あげました。本日やりたいです。

**Comment by dh-megane** [comment]
データ作成（２件）しました。１件は募集終了で作成しています。
募集中の方はSlackにもチャンネル作って参加できるようにしています。

userのページも可能であれば、皆さん値を設定して下さい。

**Comment by tsu-nera** [comment]
とりあえず結構たまったので、閉じる
