### ISSUE TITLE
入力フォームの文字数制限の設定

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#199]

**Comment by takahashi19** [comment]
タイトル文字数と投稿文字数の制限。
DB設計

**Comment by shikky0331** [comment]
user/show edit
・都道府県　ローマ字で最大9文字
・URLの長さは
IE11： 2083
Google Chrome： 32464
Firefox： 32491

https://computer-technology.hateblo.jp/entry/2016/03/24/Web%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AEURL%E3%81%AE%E9%95%B7%E3%81%95%E3%81%AF%EF%BC%8C%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%AEGET%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E5%88%B6

**Comment by dh-megane** [comment]
対応したのでクローズ。
