### ISSUE TITLE
ダッシュボード機能(取りまとめ）

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#201]
#153 
#156 
#157

**Comment by tsu-nera** [comment]
これはSlimではきつい気がする。Vue.jsをつかいたい。ひろもとさんにがんばってもらうか・・・。

**Comment by tsu-nera** [comment]
この機能、バックエンドが不要なので、Vue.jsで完結する。
Vue.jsかける人材の確保ができないと、実装は見送るしかない。

**Comment by takahashi19** [comment]
Vue.jsがかける方は見つからなかったので棚上げにします
