### ISSUE TITLE
トップページタイトルがプロジェクト一覧となってる

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#202]
Meister Hackersとしたい。よろしくおねがいします。

**Comment by dh-megane** [comment]
これはタイトルを修正して欲しいということで良いですか？
（Navbarの直下の文言を直すで合ってますか）

現在

![2019-02-27 1 11 26](https://user-images.githubusercontent.com/40923242/53427830-fc74dd00-3a2c-11e9-94c1-6a8717ebb9f1.png)


修正イメージ

![2019-02-27 1 12 07](https://user-images.githubusercontent.com/40923242/53427878-10204380-3a2d-11e9-858c-69917b4841fb.png)

**Comment by tsu-nera** [comment]
はい

**Comment by dh-megane** [comment]
修正完了したので、クローズします。
