### ISSUE TITLE
障害報告のGitHub Issueリポジトリ作成

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#203]
よろしくおねがいします

**Comment by takahashi19** [comment]
このサイトにバクがあればイシューをユーザーに立ててもらう専用の障害報告用のレポジトリ作成

**Comment by takahashi19** [comment]
これって調べたんですが命名規則は見つかりませんした。
「meister-hackers-bugs」みたいな名前で作ってもいいですか？

@tsu-nera

**Comment by tsu-nera** [comment]
はい

**Comment by tsu-nera** [comment]
meister-hackers-support

**Comment by takahashi19** [comment]
https://github.com/WEBsinjyuku/meister-hackers-support
作成致しました。
