### ISSUE TITLE
2019/02/27 もくもく会 19:00 - ルノアールニュー新宿３丁目店 

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#207]
## 情報共有

- [x] DIVE INTO CODE DEMODAYの中間発表資料のレビュー(@takahashi19 )
- [x] 開発メンバー募集について

## 技術検討

- [ ] 4/9 DEMODAYに向けた機能追加検討
- [ ] 探索的テスト

**Comment by tsu-nera** [comment]
## DEMODAYに向けた機能追加検討について

ひろもとさんいわく、インパクトのある機能を追加しないと優勝は難しい。なので、以下を提案したい。

* サービス面の拡充  @takahashi19 
* チャット機能   @dh-megane @shikky0331 
* ダッシュボード機能  @LeonardoMatusaki @hiromoto-kazuya

**Comment by tsu-nera** [comment]
##  開発メンバー募集について

* あと1,2 人くらいほしい。
* 可能ならば、ルーキー @takaaa220 を勧誘したい。
* 3/1はメンバー募集枠で発表できないか？
* @tsu-nera は３月から就活のため、活動時間が落ちます。

**Comment by takahashi19** [comment]
１開発メンバー募集について→3月1日のLT会、Vue.jsのエンジニアのみ募集しデザインはレオさん担当

２次のもくもく会→多分日曜日（3月3日）改めて日程を流す。

３追加機能→ダッシュボードとチャット機能の二つ。ダッシュボード機能はその機能だけ別サイトに分け
　　　　　　る可能性有り

４探索的テスト→募集を投稿したところherokuがエラーになる。今後は小まめにmergeとテストを繰り返す必要性有り
