### ISSUE TITLE
Footer改善

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#208]
すみません・・・マージしてから気づきましたが、以下の改善をお願いします :bowing_man: 

* ロゴの色をいじるのは禁止事項だったと思いますのでcssの適用を外したいです
* Meister-Hackers -> Meister Hackers
* 〜comment〜 -> エンジニア/未経験エンジニアがOSSでチーム開発をする事を支援するアプリ
* About us -> 私たちについて

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/e54d3f3600158b282629d9efb8cadac2/raw)](https://gyazo.com/e54d3f3600158b282629d9efb8cadac2)

**Comment by takahashi19** [comment]
footerが上がってしまっているのですが・・・改善できそうですか？

**Comment by shikky0331** [comment]
確認して修正しておきます！

**Comment by shikky0331** [comment]
![2019-02-28 11 16 53](https://user-images.githubusercontent.com/45489481/53536640-70f16e00-3b4a-11e9-9e58-f2b1c511cab3.png)

footerを上がらないようにはできたのですが、画像のようにプロジェクト新規登録と被ってしまいます。
・twitterなどのアイコンを左にずらした方がよろしいでしょうか？
・それとも新規登録を上にずらした方がよろしいでしょうか？

**Comment by takahashi19** [comment]
新規登録がどうなってるんでしょうか笑
その状態でPullRequestをあげていただいてWIPというlabelだけつけておいていただいてもいいですか。ちょっと状況みてみますね

**Comment by takahashi19** [comment]
一旦完了のためクローズ

**Comment by takahashi19** [comment]
これまた復活してますので修正します
