### ISSUE TITLE
プロジェクト一覧画面 プロジェクト新規登録ボタン押下時の挙動怪しい

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#213]
### プロジェクト新規登録ボタン押下時、”Mustache” 構文(二重中括弧)が表示
＊ローカル環境で確認 GitHubログインを実施していない場合に発生するか？

![2019-02-28 0 22 10](https://user-images.githubusercontent.com/40923242/53501173-137c0380-3aef-11e9-90b6-64e0e83eba25.png)

**Comment by dh-megane** [comment]
JSONは取得出来ていたので、バインディングが実行されていない模様。

**Comment by tsu-nera** [comment]
廣瀬さんのやつだとおもいますが、見た目的なインパクトが大きいので早く解決するために、私が着手します。

**Comment by tsu-nera** [comment]
あれれ、発生条件は記事が登録されていないときかな？？

**Comment by tsu-nera** [comment]
記事登録がないときも再現しなくなった。

**Comment by tsu-nera** [comment]
これは、おそらくturbolinksの問題で、 #231 によってなおったぽい。
