### ISSUE TITLE
リダイレクト？ エラー画面の表示（Rails）

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#214]
画面遷移の間にアドレスバーにフォーカスを当てると、
「ERR TOO MANY REDIRECT」が表示される。

Rails単体だとマルチクリック（複数回押下）は制御できないのか？
JavaScript / jQuery が必要かも？
![2019-02-28 0 34 59](https://user-images.githubusercontent.com/40923242/53502353-3c9d9380-3af1-11e9-8cd1-251dbd5e8c7d.png)

**Comment by hiromoto-kazuya** [comment]
この事象がきちんと把握できないのですが、posts#newで投稿ボタンを押した後にマルチクリックの生業がしたいっていうことでしょうか？？

**Comment by tsu-nera** [comment]
これはわたしも把握していないですね。。。

**Comment by dh-megane** [comment]
一覧画面の新規プロジェクト作成ボタン(newへの遷移ボタン)を押下すると、少しの間画面が固まります(新規投稿への遷移が出来ない事が原因だったと思われる)。

反応がないなーと思って複数回押す(マルチクリック)ことが可能であり、やっぱり反応が悪いと思って適当にアドレスバーを触るとエラーになります。
今は直っているかもです。

登録画面(new)でマルチクリックが出来る(複数リクエストが送信)と、id違いの同じpostデータができるのではと少し心配している感じです。

**Comment by dh-megane** [comment]
すみません。
一言で書くとマルチクリックは制御した方が良いのではということです。

**Comment by hiromoto-kazuya** [comment]
> 反応がないなーと思って複数回押す(マルチクリック)ことが可能であり、やっぱり反応が悪いと思って適当にアドレスバーを触るとエラーになります。
今は直っているかもです。

posts#indexページ下部に現れる移動式の`プロジェクト新規登録`ボタンですかね？
触っている感じ、反応はグッドです！廣瀬さんの読み通り治っているのかも！


> 登録画面(new)でマルチクリックが出来る(複数リクエストが送信)と、id違いの同じpostデータができるのではと少し心配している感じです。

posts#new→posts#createへと遷移する`新規作成`ボタンは複数回クリックできないように制御されてますよー！

**Comment by dh-megane** [comment]
承知しました。
ありがとうございます😊

**Comment by hiromoto-kazuya** [comment]
お時間ある時に@dh-megane さんに挙動確認してもらって、問題なさそうであればこのissueはcloseしちゃっていいかと！

**Comment by dh-megane** [comment]
挙動確認してもんだいありませんでしたので、クローズします。
