### ISSUE TITLE
ログインしていないのに新規投稿ボタンが表示される

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#216]

**Comment by dh-megane** [comment]
これは自分が修正したいですが、high priorityなので作業できる方はお願いしても良いですか？
index.html.slimを修正するだけです。
```
- if user_signed_in?
  .div.footer-btn
    a.button.is-dark href="/posts/new" プロジェクト新規登録
```
にすれば良いだけなので

**Comment by hiromoto-kazuya** [comment]
> これは自分が修正したいですが、high priorityなので作業できる方はお願いしても良いですか？
> index.html.slimを修正するだけです。
> 
> ```
> - if user_signed_in?
>   .div.footer-btn
>     a.button.is-dark href="/posts/new" プロジェクト新規登録
> ```
> 19:00頃で良ければ、自分で修正します。

こちら#232 で対応ずみです〜

**Comment by tsu-nera** [comment]
ありがとうございます。こちらは重複なので閉じます。
