### ISSUE TITLE
ヘッダーとコンテンツの幅が少ないのでひろげたい

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#226]
[![Screenshot from Gyazo](https://gyazo.com/d40730fa0a564091baeb240d7f4a49dc/raw)](https://gyazo.com/d40730fa0a564091baeb240d7f4a49dc)

**Comment by shikky0331** [comment]
![2019-02-28 15 26 20](https://user-images.githubusercontent.com/45489481/53545587-4fee4480-3b6d-11e9-9f24-486fbf9c4e0d.png)
![2019-02-28 15 26 28](https://user-images.githubusercontent.com/45489481/53545593-57155280-3b6d-11e9-9df4-b456722dc66e.png)

こんな感じで良いんでしょうか？

**Comment by tsu-nera** [comment]
ありがとうございます。

写真のバーの間に白い余白が空くくらいがいいですね。
[![Screenshot from Gyazo](https://gyazo.com/0b8c3f01803ecd136b17e21616778d0c/raw)](https://gyazo.com/0b8c3f01803ecd136b17e21616778d0c)

**Comment by shikky0331** [comment]
![2019-02-28 15 41 16](https://user-images.githubusercontent.com/45489481/53546299-5087da80-3b6f-11e9-8e5b-f07442cd6d37.png)
余白つけると付けるとプロフィール画像の上部分が違和感ありますかね、、
ここはvueで直さないとですか？

**Comment by tsu-nera** [comment]
わたしはあまり違和感はないですね。他の人の意見もききますかね。

**Comment by takahashi19** [comment]
これでいいと思いますー！PullRequestあげてください

**Comment by takahashi19** [comment]
@shikky0331 
PullRequestで @hiromoto-kazuya さんからReviewあったのでmergeしてこちらcloseしてください
