### ISSUE TITLE
トップページだけ、ヘッダーがコンテンツにつられて縮小している

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#228]
[![Screenshot from Gyazo](https://gyazo.com/37df6001d9502ba6465897155f59fdee/raw)](https://gyazo.com/37df6001d9502ba6465897155f59fdee)

**Comment by takahashi19** [comment]
これ一旦僕がやりますねー

**Comment by takahashi19** [comment]
ボディの持ってるwidthとheightの領域が変更されてますねー。これで全体的にバグってます。footerも表示されてないです。

**Comment by tsu-nera** [comment]
マージした
