### ISSUE TITLE
ユーザページと個別投稿表示機能を共通化する

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#235]

**Comment by tsu-nera** [comment]
最後、これをやったら今日は安泰

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/9d0643be3f05ac28fae0dd46c799aba6/raw)](https://gyazo.com/9d0643be3f05ac28fae0dd46c799aba6)
[![Screenshot from Gyazo](https://gyazo.com/5e893678f1c2008631a1c605cc2dd545/raw)](https://gyazo.com/5e893678f1c2008631a1c605cc2dd545)

**Comment by takahashi19** [comment]
アサイン変えます。

**Comment by tsu-nera** [comment]
忘れたので閉じる
