### ISSUE TITLE
ログイン・ログアウトでへんなメッセージがでるようになった

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#236]
[![Screenshot from Gyazo](https://gyazo.com/1fbc4483478e7fbc6dc0df8d95bc0f36/raw)](https://gyazo.com/1fbc4483478e7fbc6dc0df8d95bc0f36)

**Comment by tsu-nera** [comment]
[![Screenshot from Gyazo](https://gyazo.com/1d5152308549c928490572640465e590/raw)](https://gyazo.com/1d5152308549c928490572640465e590)

**Comment by tsu-nera** [comment]
deviseの日本語翻訳がないようにみえる・・・ 🤔

**Comment by hiromoto-kazuya** [comment]
#237ですねー、あとでdevise日本語化しておきます！
