### ISSUE TITLE
DIC提出資料作成

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#241]
[![Screenshot from Gyazo](https://gyazo.com/fd65e52f87832543c2919658d3782229/raw)](https://gyazo.com/fd65e52f87832543c2919658d3782229)

**Comment by takahashi19** [comment]
### 1課題
ターゲットが感じている解決すべき上位３つの課題
### 2顧客セグメント
どんな人がターゲットか
### 3独自の価値提案
どうなれば独自の価値を感じてくれるか
### 4ソリューション
どうやってその課題を解決するか
### 5チャンネル
どうやってターゲットにアプローチするか
### 6収益の流れ
どのように収益化されるか
### 7コスト構造
コストはどれくらいかかるか
### 8主要指標
どの数値があれば成功と言えるか
### 9圧倒的な優位性
他者に真似されないものは何か

**Comment by tsu-nera** [comment]
## レビュー指摘(tsu-nera)

### 1課題

* 一つに絞るとすると、どれを選びますか？
* 2のターゲットを定義して、そのあと1な気がする・・・。

### 2顧客セグメント

**Comment by takahashi19** [comment]
3月9日向けて再度考案。

**Comment by tsu-nera** [comment]
こちら、引き継ぎます。

DEMODAYに向けて白紙ベースでもう一回検討します。それは、高橋さんと私の意見が対立しているわけではないです。(私の意見なんてなくてもよいのです)。

聴き手は投資家で、ユーザがお金を払ってでも解決したい悩みという観点が今の私たちのサービスにはないため、DEMODAY用にロジックを再構築する必要があると考えたからです。

これはDEMODAY用なので、そのアイデアで優勝したからといって、それを今後も実行していくというわけでもありません。DEMODAYで優勝するために考えた、銀の弾丸で勝負します。

**Comment by tsu-nera** [comment]
https://cnvs.online/en/lean/-L_37YI6c0e8L4VdELrC

**Comment by tsu-nera** [comment]
https://app.detoolbox.com/projects/46241

**Comment by takahashi19** [comment]
#276
引き継ぎ
