### ISSUE TITLE
ユーザ編集がログアウト中でもできてしまうので対策をする

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#244]
ただログアウトした後、URLバーに`users/自分のiD/edit`と入力すると、自分のページ編集できちゃうので、そこはバックエンドの制御が必要ですねー！
https://github.com/WEBsinjyuku/meister-hackers/pull/234#pullrequestreview-208947888

**Comment by takahashi19** [comment]
3月7日〜8日に予定

**Comment by tsu-nera** [comment]
対処中 #313
