### ISSUE TITLE
2019/03/03 もくもく会&ミーティング定例会(Connecting the Dots) 10:00~19:00 渋谷

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#248]
## 情報共有

- [x] 議題の確認・司会、議事録の確認
- [x] 今週の実績
- [x] 来週の予定
- [x] 悩み・課題の共有
- [x] その他連絡事
- [x] 来週の平日夜のもくもく会の場所と日程の決定
- [x] 3/1のLT会の振り返り
- [ ] DEMODAY中間発表資料レビュー (@takahashi19 )
- [x] タスク管理引き継ぎ(高橋さんか廣瀬さんに引き継ぎたい）(@tsu-nera )
- [x] DEMODAYに向けた開発項目の検討

## 技術検討

- [ ] xxx

**Comment by tsu-nera** [comment]
## 週報(テンプレート)

### 今週の実績

### 来週の予定

### 課題

### その他連絡事項

**Comment by tsu-nera** [comment]
## 週報(tsu-nera)

### 今週の実績

* v1.0.0リリースに向けたバグつぶし
* マイページ表示・編集

### 来週の予定

なし

### 課題

なし

### その他連絡事項

3/1以後は就活のために稼働時間を減らそうと考えています。具体的には、以下は継続します。

* 定例会参加
* 設計・アーキ検討
* レビューア

以下はしません。

* タスク管理
* コーディング

よろしくおねがいします。

**Comment by tsu-nera** [comment]
## 3/1 LT大会の振り返り

* 高橋さんの発表の反響と新規メンバの応募状況共有
* 定期開催するかの検討
* Slackコミュニティをどうやって大きくするかの検討

**Comment by tsu-nera** [comment]
## タスク管理引き継ぎ

今まで @tsu-nera が行っていたことを @takahashi19 さんか @dh-megane さんに引き継ぎたい。

* @tsu-nera のコミット時間が少なくなるので、全体の状況に目が届かなくなるため。
* タスク管理はそれなりに作業負荷が高いため。

**Comment by dh-megane** [comment]
## 週報 (dh_megane)

3/3は10:00〜11:00が通院なので渋谷(Connecting the Dots)は12:00頃に着く見込。

### 今週の実績

先週は週報を記載しなかったので、実績のみ記載（予定対比はなし)

- 担当機能（index）の実装
　完了しMasterへマージ（本番環境へリリース）

- 機能連携で発覚したバグ、仕様考慮漏れ対応

- 削除・募集終了機能 #116 
　WBS洗い出し、実装着手　　　

### 来週の予定
- 実装
　- 削除・募集終了機能
　- チャット機能
　- マッチング時のメール送信かGitHubへのリンク貼る（？）

### 課題
特になし。

### その他連絡事項
　3月15日までは仕事が忙しい可能性が高い...。

**Comment by dh-megane** [comment]
各議題を丁寧に拾うと2.0〜2.5hくらい時間が必要だと思うので...
下記くらい(45〜55分程度)まで議題を絞れますか？

- [ ] 議題の確認・司会、議事録の確認 3分
- [ ] 悩み・課題の共有 3分
- [ ] タスク管理引き継ぎ(高橋さんか廣瀬さんに引き継ぎたい）15分
- [ ] DEMODAYに向けた開発項目の検討とタスク担当者確認 15分
- [ ] その他連絡事項 3分
 - 来週の平日夜のもくもく会の場所と日程の決定
- [ ] DEMODAY中間発表資料レビュー 5分
 - @takahashi19が困っていることを確認する
＊レビューは長時間になると思うので定例会では扱って欲しくない。
各自都合が良い時にissueを確認して会話 / コメントする方式にできると嬉しい。

**Comment by hiromoto-kazuya** [comment]
## 週報(ヒロモト)

### 今週の実績
- 3/1前のバグ回収
- 投稿/編集機能

### 来週の予定
未定。割と面接多めなのでたくさんは時間避けないかも。

### 課題

### その他連絡事項

**Comment by shikky0331** [comment]
**週報(しき)**
**今週の実績**
・footerの作成
・バグ修正
・API仕様書の作成
**来週の予定**
月曜日の面談次第です。わかり次第報告します。
**課題**
**その他連絡事項**

**Comment by LeonardoMatusaki** [comment]
## 週報 (dh_megane)

### 今週の実績

show画面のAPI繋ぎこみ

- 担当機能（index）の実装
　showページ

- 機能連携で発覚したバグ、仕様考慮漏れ対応
　不明　　

### 来週の予定
- 実装
　- なし
- デザイン
　- 全ページ

### 課題
特になし。

**Comment by takahashi19** [comment]
デザインの細かな設定（）

・WEBタスク

優勝を目指す

機能追加
・チャット機能
機能改善
・メール送信
・マークダウン形式
・テンプレート

ロープライオリティ
・Vue.js二人
・ダッシュボード機能（3つに分ける）

**Comment by dh-megane** [comment]
議事録
### 悩み課題の共有
@takahashi19
 ・コンセプトを@tsu-neraと再度検討する
 ・ランディングページを作るか
@hiromoto-kazuya
 ・未ログイン時のコメント投稿制限が必要だと気づいた。
@LeonardoMatusaki
 ・デザインを作るにあたり、追加する機能を確定して欲しい。

### タスク管理引継ぎ
・コンセプト確定後、@takahashi19か@dh-meganeに依頼する

### DEMODAY
- チャット 見送り
- ダッシュボード 見送り
- マッチング時のメール送信
　代替手段：Slack / 連絡先記載
- 機能改善　
 　URLチェック
 　テンプレート機能
 　デザイン
 　Vue.js移行

**Comment by dh-megane** [comment]
要点を書いた議事録も記載済み。
クローズ。
