### ISSUE TITLE
掲示板記事編集で、リポジトリ欄はURLをひょうじできないか？

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#257]
refs

https://github.com/WEBsinjyuku/meister-hackers/pull/253#pullrequestreview-209313363

**Comment by dh-megane** [comment]
URL解析メソッドは新規登録時のみ実行するように変更したので
カラムを追加する必要は無くなった。
URL形式で表示したい理由もないはず（項目がdisabledなのでリンクとしても使えないので）

クローズ。
