### ISSUE TITLE
プロジェクト一覧画面 Mustash {{ }} が見える

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#258]
#213 で対応完了を確認して頂いているが、
https://meister-hackers.herokuapp.com/posts/# 
といったアドレスでアクセスすると、一瞬Mustash {{ }} が見える。

URL改変してアクセスは例外操作っぽいので、優先度は低い...。

**Comment by takahashi19** [comment]
こちら僕がアクセスすると見えないのですがバグ自体改善されていますでしょうかー
改善していればcloseお願いします。
[![Screenshot from Gyazo](https://gyazo.com/3bd8232513b867cdf2de71119c0bf1fd/raw)](https://gyazo.com/3bd8232513b867cdf2de71119c0bf1fd)

**Comment by dh-megane** [comment]
回答遅れました。
やはり{{}}は若干見えました。

ユーザ詳細画面も「自己紹介文なし」みたいな文章がチラついてました。

Vueを全画面展開する際に、対応できればと思ってます。

**Comment by takahashi19** [comment]
これ確かに見えますね。Vue.jsを勉強していた下記の方法を見つけたのですがいかがでしょうか
①[こちらの記事](https://qiita.com/macoshita/items/630e6bf1b6fa068790a3)v-cloakを使う
②head内にCDNを入れて読み込ませる
[![Screenshot from Gyazo](https://gyazo.com/facb08a4e2a63fe31a42f68c90904df7/raw)](https://gyazo.com/facb08a4e2a63fe31a42f68c90904df7)

**Comment by tsu-nera** [comment]
修正されたのかな？よくわからないので閉じる。
