### ISSUE TITLE
【仕様検討】応募者と起案者の直接のやり取りposts/show

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#267]
posts/show
①アクションメール
　・「参加ボタンを押す」というメールが飛ぶ
　・メールアドレスはGitHubより取得したものを使用する。
　・メール内容
　　タイトル：参加希望者がいます
　　［］
　・その後のやり取りはメールで行ってもらう
②本アプリと連動したSlackのワークスペースに誘導しその中でやり取りしてもらう
　方法１
　・Slackに参加する際に必ずこちらと同名でアカウントを作成するというルールを設ける。
　・Slackにてメンバーの中から探して当人同士でDMでやり取りをしてもらう
　方法２
　・Slackに募集と連動した募集専用チャンネルを設置しアプリと連動させる→要調査
③GitHubのリポジトリにやり取り専用issueを立ててもらう
　・
④チャット機能の実装
　・「参加ボタン」を押す→個別のチャットルームに飛ぶ
　・

※要調査・・・機能として調べる必要あり

**Comment by dh-megane** [comment]
内容確認しました。
3/9までの優先順位は①アクションメールを検証・調査して、
間に合わない場合は「②SlackのURL表示」で良いですよね？

担当者決めは @takahashi19 にお願いします。

**Comment by takahashi19** [comment]
基本的に @dh-megane さんの②案か②とSlack併用が良いかと考えますが
②の案について技術的に3月9日まで間に合うか少し不安です。その点ご意見を聞きたいです

**Comment by dh-megane** [comment]
回答遅れました。
３月９日にメールサーバを用意/画面を新規作成するのはと間に合わないと思います。

ひとまず、ＳlackのURLを表示させましょう。投稿画面の項目追加、postsテーブルのカラム追加が必要。

**Comment by takahashi19** [comment]
仕様
①posts/show
　1つ目：スラックコミュニティ（meister-hackers）参加ボタンの作成
　・スラックのコミュニティに参加できるボタンを作る
　　・URLは無限リンク
　2つ目：posts/newで投稿したチャンネル名の表示
②posts/new
  ・projectの専用チャンネル（string）を投稿させてる

ユーザーにはこちらで用意したSlackコミュニティmeister-hackersの中でやり取りをしてもらう形でいかがでしょうか？
