### ISSUE TITLE
2019/03/10 ミーティング定例会 22:00~23:00

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#272]
## 情報共有

- [x] 議題の確認・司会、議事録の確認
- [x] 今週の実績
- [x] 来週の予定
- [x] 悩み・課題の共有
- [x] その他連絡事
- [x] 13日のコードレビュー/今後の活動について　#284
[スプレットシート](https://docs.google.com/spreadsheets/d/1gdFeW1-jn2NKPkbkUOmxPPJvo_Xgl0sA8zyfoMU_U18/edit#gid=0)
- [x]  次回のもくもく会の開催日程（できれば水曜日に一度集まりたい）

## 技術検討

- [ ] xxx

**Comment by takahashi19** [comment]
## 週報(テンプレート)

### 今週の実績

### 来週の予定

### 課題

### その他連絡事項

**Comment by dh-megane** [comment]
## 週報(dh-megane)

### 今週の実績
- 新デザイン適用（posts/index)
- PRレビュー

### 来週の予定
- 検討中（後で記載します）

### 課題
- 無

### その他連絡事項
- 納期の都合で来週まで仕事が忙しい（PRレビューで精一杯かも）
   18日以降は、2hは安定して活動できるかと。

**Comment by tsu-nera** [comment]
## 週報(tsu-nera)

### 今週の実績

* リーンキャンパスシート作成

### 来週の予定

* 隠居

### 課題

* 確定深刻...

### その他連絡事項

マジで確定深刻やらせてください！開発止めます。

**Comment by LeonardoMatusaki** [comment]
## 週報(テンプレート)

### 今週の実績
* LPのデザイン
* プロジェクト個別表示のデザイン修正
* プロジェクト作成・編集画面のボタンのデザイン修正（必要なかったかもです。）
* ヘッダーのデザインの修正
* フッターのデザインの修正

### 来週の予定

### 課題

* 確定申告😭

### その他連絡事項

**Comment by hiromoto-kazuya** [comment]
## 週報(テンプレート)

### 今週の実績
デザインとか参加手順説明モーダルとか

### 来週の予定
未定

### 課題
特にないっす

### その他連絡事項

**Comment by shikky0331** [comment]
## 週報(テンプレート)
### 今週の実績
デザインの再適用、404pageなど
### 来週の予定
日程は未定だが面接あり
### 課題
特になし
### その他連絡事項

**Comment by takahashi19** [comment]
## 週報(takahshi19)

### 今週の実績
・タスク管理
・渉外
・フロント一部実装
### 来週の予定
・就活次第
・残存するPRのレビュー
・LPの作成
・500ページ
### 課題
・labelやプロジェクト管理の方法。
・今後のタスク整理
### その他連絡事項
・次は水曜日の夜に新宿三丁目のルノアールでやりたい
