### ISSUE TITLE
投稿画面 content 初期表示時にテンプレート表示

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#273]
定型文を表示できないか（3/3定例会で確認)

**Comment by takahashi19** [comment]
【募集概要】
GitHubのオープンソースで作る予定なので就活用に制作物を作りたい方、個人アプリの作成をチームでやってみたい方を募集

【開発概要】
GitHubで開発したい人と開発に協力したい人をマッチングすることを目的とするWebサービスを開発をします

【対象者：以下のいずれか一つに当てはまる方】
プログラミングの職業訓練校/専門/民間のスクールに在学/卒業している。
Twitterクローン等の簡易アプリ開発経験がある。
ProgateのRuby/Railsをすべてやったことがある。
Railsチュートリアルを一度やった事がある。

【参加条件】
①GitHubと②Railsの開発に興味がある事
毎週2回の打ち合わせに参加できる人（水曜日と休日）
チーム開発に協力的な方（教え合ったりする事ができる方）
3月1日までjoinが可能な方

【この開発を通じて得られるモノ】
就活用/実績用の制作物
GitHubを用いたチーム開発の経験
Ruby on Railsの開発経験
チーム開発者同士の技術交換

【開発環境（技術選定）】
バックエンド
Ruby 2.6
Rails 5.2.2
フロントエンド
Slim
Vue.js
Bulma
DB
PostgreSQL
インフラ
Heroku
開発環境
Slack
GitHub
Google App
連携サービス
CirCleCI
Sider

【その他】
工期：６週間（予定）

【活動拠点】
渋谷または新宿

**Comment by tsu-nera** [comment]
いったんとじる
