### ISSUE TITLE
MyPageForm キャンセルボタン押下時にFlashメッセージ表示される

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#274]
MyPageFormのキャンセルボタン押下時にMyPageへ遷移するが
Flashメッセージが表示されている。( @shikky0331 指摘 )

**Comment by shikky0331** [comment]
すみません！僕の説明が悪かったです！
最新のmasterではFlashメッセージは表示されないのですが、
![2019-03-04 11 49 07](https://user-images.githubusercontent.com/45489481/53707790-c9d74400-3e73-11e9-8269-aab3ee75ebe5.png)
ハイライトしている部分にFlashを追加すると
![2019-03-04 11 49 24](https://user-images.githubusercontent.com/45489481/53707814-e4a9b880-3e73-11e9-90cf-2e651b00c66a.png)
キャンセルを押すと
![2019-03-04 11 49 29](https://user-images.githubusercontent.com/45489481/53707824-effce400-3e73-11e9-9c37-760bfa47ee5e.png)
編集を成功しましたと表示されてしまいます。

これをcontrollerで修正したかったのですが、上手くいかなかったのでどうすればいいのかと、、

①controllerで修正すればいいのでしょうか？
②vue.jsでキャンセルボタンを押した際にupdate actionが反応しないようにして、プロフィール画面に遷移させた方がいいのでしょうか？

**Comment by dh-megane** [comment]
説明ありがとうございます😊
承知しました。

updateアクションメソッドが実行されるのが変だと思うので、vue.js(js)の修正だと思います。

「/users/2/」の最後の「/」が原因っぽい気がします。

**Comment by shikky0331** [comment]
キャンセルボタンを押すとmethodsのcancelに入るのですが
![2019-03-05 22 55 06](https://user-images.githubusercontent.com/45489481/53810453-52e89b00-3f9a-11e9-90fd-71ab8389416f.png)

cancel ( )が終わるとsubmitに入ってしまいます。
![Uploading スクリーンショット 2019-03-05 22.57.33.png…]()

なのでupdateアクションが実行されてしまっていると思うのですが、解決方法がわからなくて悩んでいます、、
誰かわかる人いたらお願い致します。

**Comment by tsu-nera** [comment]
あ、もしかしてわたしがつくったところですかね？わたしもちょっとみます。

**Comment by tsu-nera** [comment]
すみません、バグでした。 type="button"を追加してください

```javascript
            button.button(type="button" @click="cancel") キャンセル
```

https://stackoverflow.com/questions/3314989/can-i-make-a-button-not-submit-a-form

**Comment by dh-megane** [comment]
@shikky0331
```
form(@submit.prevent="submit")
``` 
上記のように記載することでボタンクリック時にデフォルトの
submit関数をprevent（動作させない）しています。
preventさせるのは、Vue.jsのPOST通信時のお約束らしいです。

preventさせて、代わりにscriptタグに記載したsubmit()を実施。
（下記methods参照）
```
  methods: {
    submit() {
      const baseUrl = location.href;
      const profileUrl = `${baseUrl.replace("edit", "profiles")}/${this.profile.id}`;
      Axios.put(profileUrl, this.profile)
        .then(() => {
          location.href = baseUrl.replace("edit", "");
        });
    },
```


本題ですが、Buttonタグのtype属性の初期値は「type=submit」らしく
クリックすると上記のsubmit関数 / submit() が実行されるようです。

なので、type属性をbuttonにしてsubmit関数を呼ばないようにするか
click時のデフォルト振舞いがsubmitらしい（？）のでpreventして
cancel()のみを発火させる方法があります。
```
button.button(type="button" @click.prevent="cancel")　または
button.button(@click.prevent="cancel")
```

ただButtonタグのClickのデフォルト振舞い記事があまりないので
@tsu-nera さんが提案した「type="button"」を採用したほうが良いと思います。

すぐに解決策を導けず、申し訳なかったです... (＞人＜;)

**Comment by shikky0331** [comment]
原田さん、廣瀬さん詳しく説明までありがとうございます！
追加しておきます！

廣瀬さん大丈夫です！
自分も一人で解決できるように頑張ります！！😊

**Comment by shikky0331** [comment]
解決したためclose
