### ISSUE TITLE
3/9までの作業計画

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#275]
@takahashi19 
現時点で挙がっているタスク一覧を纏めました。
3/9までに行うべきタスク分け、タスク割当の検討をお願いします。
困ったら相談して下さい。

機能改善・障害一覧
・#281 ガチ募集、ゆる募集 
・#170 デザイン再適用(Vue.js移行)
・#274 MyPageForm キャンセルボタン押下時にFlashメッセージ表示される
・#273 投稿画面 content 初期表示時にテンプレート表示
・#272 【ロゴ作成】navbar&favicon
・#267 参加ボタン押下時処理（応募者／起案者の連絡手段)
・#265 GitHubリポジトリURLチェック処理 @shikky0331 仕掛中
・#263 未ログイン時のコメント投稿制限
・#258 プロジェクト一覧画面 Mustashe{{}}が見える
・#244 ユーザ編集がログアウト中も可能である。
・#199 入力フォームの文字数制限の設定
・#174 Markdown対応/募集記事に画像埋込
・#117 ランディングページ作成
・#86  GitHubAPI 並列実行(index)
高橋追記
・#279 404・503ページの作成（デザイン有り）

**Comment by takahashi19** [comment]
#170 にまとめたためclose
