### ISSUE TITLE
サービス戦略策定

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#276]
## CORE Concept

* 駆け出しエンジニアとベテランエンジニアをマッチングさせるサービス
* GitHubをつかったオープンソース開発を推進するサービス
* チーム開発を推進するサービス
* エンジニアのマイスター制度を作るサービス

## Refs

* http://disciplinedentrepreneurship.com/
* [Mapping The 24 Disciplined Entrepreneurship Steps using the Lean Canvas](https://medium.com/@chrpopov/mapping-the-24-disciplined-entrepreneurship-steps-using-the-lean-canvas-8ea00f4f7ee9)
* https://cnvs.online/en/lean/-L_37YI6c0e8L4VdELrC

**Comment by tsu-nera** [comment]
# 1. Market Segmentation

## Goal

* 潜在顧客とその市場のリストを作成
* ６〜１２個案を出す
* 市場に対して一次調査をする

##

**Comment by takahashi19** [comment]
#241 
（議論の前提）DIC提出資料

**Comment by tsu-nera** [comment]
## 2. 足がかり市場を決める

駆け出しエンジニア

**Comment by tsu-nera** [comment]
## 3. エンドユーザプロフィールを決定する

**Comment by tsu-nera** [comment]
## 4. 足がかり市場でのTAMの算出

最大市場規模。その市場で最大のシェアをとったときの利益。

* 予想ユーザ数(都内の就活生) ... 300人 
* 一ヶ月の費用 8 万

TAM = 2400千万

Progate: 3000人 x 1000円 = 3,000,000 / 20 = 150000円 しきさんの給料

**Comment by tsu-nera** [comment]
## 5. ペルソナ設定

* 駆け出し - 高橋さん
* ベテラン - 廣瀬さん
* リクルータ - 宮崎さん・しゅうへいさん

**Comment by tsu-nera** [comment]
[悲報]
リクルートキャリアで働いている妹にいろいろ聞きました。

> 生きるか死ぬかの人生がこれで決まりますので助けてください。

> GitHubやLinkdedInの統計情報や解析情報があったらいくらで買うか？

統計解析なら、自分たちでやってる気がする

> いや、解析の元データはわれわれのほうでプラットフォームを用意する。

データならネット系企業から買ってる気がする

> いくらで？

それこそ、大元のGoogleとかYahoo!とか。値段はしらない

> 闇の商売ですね。

それがあたりまえになっていて、共存している。

> 今に Google for Jobsが日本ではやってリクルート滅びます

競争が進むのはよいこと

> 死んだ

**Comment by tsu-nera** [comment]
## 6. 製品フルライフサイクル

あとで

**Comment by tsu-nera** [comment]
## 7. 製品仕様の視覚化

**Comment by tsu-nera** [comment]
## 8. 高次の製品仕様

*

**Comment by tsu-nera** [comment]
### 8. 製品の価値の数量化

省略

**Comment by tsu-nera** [comment]
## 9. 見込み客10人をみつける

**Comment by tsu-nera** [comment]
## 10. 事業のコアを定義する

**Comment by tsu-nera** [comment]
## 11. 市場の戦略的ポジションをとろう

省略

**Comment by tsu-nera** [comment]
## 12. DMUを定義する

あとで、ビジネスモデルを定義してから。

**Comment by tsu-nera** [comment]
13. 顧客獲得プロセスの確認

**Comment by tsu-nera** [comment]
## 14. 足がかりの次に狙う市場規模を算出する

DEMODAYのあとで検討する

**Comment by tsu-nera** [comment]
## 15. ビジネスモデルを検討する

**Comment by tsu-nera** [comment]
## 16. 価格体系を決める

**Comment by tsu-nera** [comment]
## 17. LTVの算出

あとで。

**Comment by tsu-nera** [comment]
18. 足かかり市場の見込み収益

あとで。

**Comment by tsu-nera** [comment]
## 19. COCAの算出

あとで。

**Comment by tsu-nera** [comment]
## 20. 主要な仮設の特定

あとで

**Comment by tsu-nera** [comment]
## 21. 仮設検証

あとで。

**Comment by tsu-nera** [comment]
## 22. MVBP の決定

**Comment by tsu-nera** [comment]
## 22. MVBPの実行

同上

**Comment by tsu-nera** [comment]
## 24. 製品の成長戦略

あとで。

**Comment by tsu-nera** [comment]
## 1. 課題- ターゲットが感じている解決すべき上位３つの課題

## 2. 顧客セグメント - どんな人がターゲットか

## 3. 独自の価値提案 - どうなれば独自の価値を感じてくれるか

## 4. ソリューション - どうやってその課題を解決するか

## 5チャンネル - どうやってターゲットにアプローチするか

## 6. 収益の流れ - どのように収益化されるか

## 7. コスト構造 - コストはどれくらいかかるか

## 8. 主要指標 - どの数値があれば成功と言えるか

## 9. 圧倒的な優位性 - 他者に真似されないものは何か

**Comment by tsu-nera** [comment]
findy scoty forkwall ... いろいろしているけど、すでにあるデータを取る。僕たちはデータをつくることろから始める。

- gitをもとにした技術的な評価(技術力)
- プロジェクトが終わったときの評価(チーム力) => 評価コメント機能 => 企業から評価コメントを公開

人が評価する。

- 駆け出しエンジニアの就職支援をするプラットフォーム
- 自分の市場価値を上げたいエンジニア ... 

スクールとタッグを組む。駆け出しとベテランをマッチングさせる。スクールから利用料をとる。`

1. 
- リクルーティングは入れる。
- 即戦力と、表現をとる。

**Comment by takahashi19** [comment]
こちら斎藤さんに提出してfeedbackもらいます。先ほど提出しました

**Comment by tsu-nera** [comment]
wikiに転機します
