### ISSUE TITLE
カスタムタグ「がち募」「ゆる募集」の追加

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#281]
オフライン（もくもく会）2/27(水)に出た話。
「がちな開発募集」か「ゆるめの募集」かを選べるようにする。
@LeonardoMatusaki のデザインは対応済み。

対象画面：index, show, new/edit

**Comment by dh-megane** [comment]
@takahashi19 
issueを立て忘れていました。これについても優先度を付けて頂けますか？

**Comment by takahashi19** [comment]
優先度2とさせて頂きますー理由としては3月9日の予選で優先なのは①UIを綺麗にする事と②プレゼン（サービスサイド）の２点なので、優先順位は少し低いと考えます。

**Comment by tsu-nera** [comment]
いったんとじる
