### ISSUE TITLE
コメント削除機能（個別表示画面）

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#282]
コメント削除機能を追加する（削除できるのは自分のコメントだけとする？）。
@LeonardoMatusaki のデザインは対応済み。

**Comment by dh-megane** [comment]
@takahashi19 
これも優先度を付けて下さい。

**Comment by takahashi19** [comment]
優先度2です。理由としては①参考サイトのConnpassも削除はできない
②コメントの削除はユーザーにとっては必須ではないからです（誤字等も追記すれば良いだけかなと、またやり取り系は削除できないものも多いのでユーザーにとって意外な印象にはならないかと）

**Comment by dh-megane** [comment]
本番環境で動作確認済みなので、クローズ。
