### ISSUE TITLE
DEMODAY用プレゼン資料作成

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#283]
https://docs.google.com/presentation/d/1UIiwIj0QDnvn1g8ztS57c0FAbWM3hiD-yGbTrExd8tQ/edit?usp=sharing

ども、チームWEB SHINJUKUです！本日は、我々が開発した、Meister Hackersを紹介いたします。よろしくお願いします！

我々、Web SHINJUKUは、エンジニア完全未経験の駆け出しエンジニア4人と、SIer出身のWEB開発未経験エンジニア2人の6人からなるチームです。

私たちはなんと、DIVE INTO CODE生ではありません。もともとは、去年の6月から高橋さんが主催となって毎週新宿で開催してきたもくもく会からはじまりました。わたしと高橋さんは、もくもく会を通じて、50人以上の駆け出しエンジニアの生の声をきいてきました。駆け出しエンジニアの悩みは、独学やスクール卒業レベルと現場レベルのギャップが大きいことでした。

一方、私のような実務経験があるエンジニアは、スキルアップのためにプライベート開発をしたいときの協力者がなかなかみつからないという悩みがあります。

そこで、この両者の悩みを解決するために今回提案したいことが、オープンソースで開発を進める、というものでした。オープンソース開発とは、ソースコードを世界に公開して、無償のコントリビューションによって開発するスタイルです。これだ、と思いました。すなわち、駆け出しエンジニアは実務レベルの教えをベテランエンジニアから受け、そのお礼としてプロジェクトに無償のコントリビューションをする、というものでした。このアイデアが、今回のプロダクトになります。

われわれのプロダクトでは、ベテランエンジニアがオープンソースプロジェクトの募集をサイトに投稿して、駆け出しエンジニアが投稿に応募するというマッチングの機会を提供します。

しかし、これでは投資が受けられません。そこで、エンジニア採用という第3の視点をいれます。採用担当は、実際に採用するまでエンジニアの技術力が見えにくいことが悩みでした。もちろん、既存サービスで今あるデータを解析するサービスはあります。しかし、我々のサービスは、エンジニアのみなさんに我々のプラットフォームの上で遊んでもらうことによって蓄積された生々しいデータを売ることによって、マネタイズをします。

最後に、Meister Hackersにこめた想いを語らせてください。我々は、エンジニア業界の師弟制度の復活を目指します。大学や教育機関がない中世ヨーロッパでは、マイスター制度といわれるベテランの職人が駆け出しの職人を育てる徒弟制度がありました。昨今、会社が教育に対して投資をせず、個人が会社に依存せずに成長することが求められる、これが、我々がこれから進む新時代、令和の時代でございます。新しい時代、令和において、ベテランエンジニアが中堅・駆け出しエンジニアを支援するエコシステムをつくりたい、それが我々のミッション、Maister Hackersです。

Maister Hackersは、エンジニアの成長を全力で応援します。どうぞ、よろしくお願いします。

**Comment by takahashi19** [comment]
必要なくなった。

**Comment by tsu-nera** [comment]
次回打ち合わせまでに一旦かけますか？

テンプレがあるので、それに従って作成をおねがいします。

* https://medium.com/@tumada/3-min-pitch-airbnb-203021531522

課題
解決策
市場規模
トラクション
ユニークな洞察
ビジネスモデル
チーム

**Comment by takahashi19** [comment]
プレゼン資料
【用語の説明】
・（１P）→プレゼン資料としてスライド１ページで説明という意味。全部で11P。AIRBNBピッチは14P
・各々にある①〜③は①未経験エンジニアの立場②ベテラン（師匠）エンジニアの立場③ベンチャー企業の採用担当の立場の意見を想定
・AIRBNBのピッチにのっとっているので右の資料を読み合わせながら見ていただければと思います→[こちら](https://medium.com/@tumada/3-min-pitch-airbnb-203021531522)
・△→特に意見がほしいところ。「→」は補足

【以下プレゼンの構成】
１表紙（1P）
　・目次とアプリ名

２課題（1P）
　　①未経験者にとった自身が自社開発の企業に就職できるかは重要な関心事です。
　△②実務経験者にとって後世のために技術者を増やしていく事は重要な課題です。
　△③自社開発の企業の採用側にとってミスマッチのなく人材を獲得・選考するのは大変な事です。

３解決策（1P）
　Meisterhackers：実務経験者のOSSの個人プロダクトを手伝う事を目的とした未経験エンジニアとチーム開発を行うWebプラットフォーム
　①実務のチーム開発を無料で経験したい時
△②個人プロダクトの開発を人手が欲しい手伝って欲しい時
△③より開発者のちゃんとした実力を知りたい時
　
△４市場規模（3P）
　１市場規模：IT人材の人手不足（よく見るおきまりのIT人材不足ページ）（１P）
　２個人調べのスクール月間稼働数（某スクールのアクティブユーザー100人）（１P）
　３競合ロゴ→チーム開発をやってないスクール。市場のポジション（１P）

５トラクション（1P）実際の顧客の状況
　・実際の顧客の声
　①「チーム開発のいい経験になった」「自社開発にいけたよ」
△②「手伝ってもらえて自社開発行ってくれて嬉しい」
△③「紹介があったのでコード以外の強みがわかりやすかったよ」

△６ユニークな洞察（1P）→あんまり思いつかないです。
　・僕たちの周りでは今それがTwitterなどで起こっています。

７ビジネスモデル(1P~2P)
　１最初はチーム開発を支援する研修でお金をとります。(1P)
　２稼働数が30人を超えた段階で情報を提供する事で料金をいただきます(1P)
　　△その個人が立てたissueの数、コミット数で換算した評価をその人の技術的な情報として提供し
　　　ます。
　　△推薦・チーム間評価制度によるその人のチームにおけるコミュニケーションスキルの情報を企業
　　　に提供します。
　　・金額は月額3万円で提供します。
　　　→料金は採用の媒体であるWantedlyのミニマムプランが根拠

８チーム（なぜ僕らならできるか）(1P)→これは他の方は他の方からの紹介文が必要です。
　自分：訓練校とスクールに通い良質なポートフォリオの製作に苦しみ中々自社開発にいけずどうして
　　　　いいか自分も悩んだ。また初学者向け勉強会の主催を半年間おこない同様の悩みをもつ未経験
　　　　の方がいるのも知っている。

△９. Closing Remarks
　ここは賛同してくれる企業を呼びかけるか、チーム開発をしたい人を呼びかけるか

**Comment by takahashi19** [comment]
資料
https://xd.adobe.com/view/6da5153d-d5b3-47fd-5409-3d1cfd0b0e70-1b94/

**Comment by tsu-nera** [comment]
【内容】
　・5分プレゼンその後に動作確認5分程度⇨当日の参加者数によって時間は可変現時点では不明とのこと（3月17日）
【ツール】
　・Adobe XD
【時期】
　着手時期：サービス設計終了次第
　完了時期：3月

**Comment by tsu-nera** [comment]
[悲報] 時間は３分になりました・・・
