### ISSUE TITLE
【スカウト機能】User/index

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#285]
[![Screenshot from Gyazo](https://gyazo.com/3e418f16b84b49be0927e2ce4a658b2f/raw)](https://gyazo.com/3e418f16b84b49be0927e2ce4a658b2f)
[![Screenshot from Gyazo](https://gyazo.com/fc9dbbbf30c9dea5de31641621e1e9e2/raw)](https://gyazo.com/fc9dbbbf30c9dea5de31641621e1e9e2)

**Comment by takahashi19** [comment]
目的：起案者側（集めたい側）からも登録ユーザーにアクセス出来る様にする事でよりチームマッチングを活性化させる。
機能仕様
・user/showページに「連絡する」機能を追加し起案者側からもアクセスできるようにする。
・user/indexを作成する。
　・名前
　・アイコン
　・都道府県
　・説明文

**Comment by tsu-nera** [comment]
いったんとじる
