### ISSUE TITLE
[ユーザ管理機能] 推薦文機能

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#286]
OSSへのコントリビューションの対価としての推薦文です。

**Comment by takahashi19** [comment]
これは僕たちサイトの運営者が開発チームのそれぞれ個人に発行する推薦文のイメージですか？

それとも起案者（中堅エンジニア）がチームメンバーに発行する推薦文ですか？

**Comment by tsu-nera** [comment]
ユーザ同士です。駆け出しがベテランにも書きますね

**Comment by tsu-nera** [comment]
いったんとじる
