### ISSUE TITLE
posts/show ボタンがfooterに突き刺さる

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#303]
[![Screenshot from Gyazo](https://gyazo.com/d59d09393dc066b8edf155a1b64a6381/raw)](https://gyazo.com/d59d09393dc066b8edf155a1b64a6381)

**Comment by dh-megane** [comment]
今はボタンの表示位置が高めになっているので改善されていると思います。
![スクリーンショット 2019-03-16 21 38 27](https://user-images.githubusercontent.com/40923242/54475636-dfb31480-4836-11e9-9a8f-05983eb90be8.png)

**Comment by takahashi19** [comment]
ちょっと確認しますね

**Comment by takahashi19** [comment]
確認しました。ありがとうございます。
