### ISSUE TITLE
デグレ posts/show 募集停止プロジェクト 編集ボタンが表示されない

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#306]
ログインユーザ = 起案者 の募集停止プロジェクトについて編集ボタンが表示されない。
![スクリーンショット 2019-03-09 13 13 57](https://user-images.githubusercontent.com/40923242/54066078-75fe9d80-426d-11e9-80a3-344b26a3716e.png)

**Comment by takahashi19** [comment]
これってもう終わっていますか？本番環境だと下記になっています
[![Screenshot from Gyazo](https://gyazo.com/1ce5c6045210b08fa72ad5e65a489ae9/raw)](https://gyazo.com/1ce5c6045210b08fa72ad5e65a489ae9)

**Comment by takahashi19** [comment]
@dh-megane 
逆に募集停止ボタンが出ていません

**Comment by dh-megane** [comment]
投稿画面で募集停止にしましたか？

**Comment by takahashi19** [comment]
いえしてませんバグの意味理解しました
[![Screenshot from Gyazo](https://gyazo.com/3a6934a4a510fc88d96acdf59e34db5a/raw)](https://gyazo.com/3a6934a4a510fc88d96acdf59e34db5a)

**Comment by takahashi19** [comment]
ここRailsでやれそうなので僕がやります

**Comment by takahashi19** [comment]
終わり
