### ISSUE TITLE
一覧表示を新しいものから古いものに並べ直したい

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#308]

**Comment by dh-megane** [comment]
@tsu-nera
#308の件、serch_posts関数でid順？かで検索をかけていたので、
status ASC, opened_on DESC でやってみましょう。
→ 募集中で、opened_on が最新順で並べる。
@takahashi
すぐ対応できるかと思うので、やって良いと思いますよ。
