### ISSUE TITLE
投稿時にコメントする際に、内容を投稿しなくても投稿できてしまう。

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#309]

**Comment by takahashi19** [comment]
確認しますがPostは内容が入ってないと投稿できないので
messageの方だと思います。

**Comment by dh-megane** [comment]
この文章を書かれたのは、野呂さんや斎藤さんですか？
本日９日にアプリを閲覧されたということですか？
さっきの障害時に見られていないならば、一安心なのですが...。

**Comment by takahashi19** [comment]
このやり取りはSlackでお願いします

**Comment by tsu-nera** [comment]
着手
