### ISSUE TITLE
デグレ posts/show リンクが青い（GitHubアイコン・username）

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#310]
本番環境で発生。
リンクコントロールが青い。マージ前は黒だったので可能であれば戻したい。
GitHubアイコンが青は気になります。

![スクリーンショット 2019-03-09 16 07 16](https://user-images.githubusercontent.com/40923242/54067615-72771080-4285-11e9-8eef-f1643a79b416.png)

**Comment by takahashi19** [comment]
これ僕が引き受けますねー

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/0b43edebf5205a63478839cc7c86adfe/raw)](https://gyazo.com/0b43edebf5205a63478839cc7c86adfe)

**Comment by takahashi19** [comment]
修正しました軽微な修正のためpullしてからmaster変更ない状態で、masterプッシュしてます。
