### ISSUE TITLE
デグレ posts/show がち募・ゆる募が表示

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#312]
イメージ確認用の「がち募・ゆる募」が表示されている。
「がち募・ゆる募」機能は未対応なので、コメントアウトして欲しい。
![スクリーンショット 2019-03-09 16 18 51](https://user-images.githubusercontent.com/40923242/54067723-0e554c00-4287-11e9-9e52-1e4312b02277.png)

**Comment by takahashi19** [comment]
終わり
