### ISSUE TITLE
posts/show 募集停止文言位置

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#315]
今の場所だと、ボタンと勘違いするので表示位置を見直す。
![2019-03-09 3 29 00](https://user-images.githubusercontent.com/40923242/54048442-2abc9e80-421d-11e9-8098-f01fa0e5516f.png)

**Comment by takahashi19** [comment]
@dh-megane 
こんな感じでしょうか。あとは「募集停止中」をいい感じにすれば良いですか。
[![Screenshot from Gyazo](https://gyazo.com/fd9ec8ee9ae7400b5590a2685fa3ca4a/raw)](https://gyazo.com/fd9ec8ee9ae7400b5590a2685fa3ca4a)

**Comment by dh-megane** [comment]
画面イメージ（配置箇所）はそんな感じです！
追加で
①フォントサイズを大きく＋太字にする
②黒以外の文字色にする（一目で募集停止とわかる感じ）
③文言はposts/indexが「募集停止」なので「募集停止」が良いかと思います。

**Comment by takahashi19** [comment]
終わり
