### ISSUE TITLE
記事投稿時のslackチャンネルの入力情報が不明

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#324]
[![Screenshot from Gyazo](https://gyazo.com/695961cbaf2cd98aa86ab3f9f61ddd1d/raw)](https://gyazo.com/695961cbaf2cd98aa86ab3f9f61ddd1d)

Slackチャンネルってどういう手順でつくるんでしたっけ？

[![Screenshot from Gyazo](https://gyazo.com/13a3656fa3ff6677f4d416cfdbce4dec/raw)](https://gyazo.com/13a3656fa3ff6677f4d416cfdbce4dec)

ばりでーしょんがあり、空入力できません。

これは、仕様レベルの致命的バグですので、最優先対応が必要です。

**Comment by dh-megane** [comment]
ひとまず仮対応として本画面にMisterHackerへのリンクを貼り登録を促すのは
どうでしょうか？
画面レイアウトのイメージ書きます。

**Comment by tsu-nera** [comment]
[![Screenshot from Gyazo](https://gyazo.com/0edc85a64ad362c3eaeba2769c5dee47/raw)](https://gyazo.com/0edc85a64ad362c3eaeba2769c5dee47)

チャンネル入力のpresense falseはどうですか？
チャンネル名は、github repository名にしてくださいと書きます。

**Comment by dh-megane** [comment]
起案者をプロジェクト投稿時にMeister HackerのSlack（ワークスペース）に参加させることが必要
（＝ワークスペースに参加すればチャンネルを作れる）なので、
presense trueの方が起案者に投稿時にワークスペースへの参加を促せると思います。

仮名でチャンネルを登録し実在しない／誤ったチャンネル名を書いた場合は、posts/showのコメント欄で参加希望者から何かしら反応があるはずです。

**Comment by dh-megane** [comment]
下記イメージでワークスペースに参加させる。
![スクリーンショット 2019-03-10 7 03 19](https://user-images.githubusercontent.com/40923242/54077914-c116c000-4302-11e9-92a9-cc6b7a11ac82.png)

**Comment by dh-megane** [comment]
本番環境での動作確認済。クローズ。
