### ISSUE TITLE
ActiveRecord find関数 結果0件の対応

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#335]
https://meister-hackers.herokuapp.com/posts/1
find関数でデータを取得できない場合にエラーになる。
エラーページかposts/indexに飛ばす必要がある

![スクリーンショット 2019-03-10 8 58 38](https://user-images.githubusercontent.com/40923242/54078831-d8f64000-4312-11e9-9fab-bc823d0b9b0f.png)

**Comment by takahashi19** [comment]
現状はエラーページ？に飛びますね
[![Screenshot from Gyazo](https://gyazo.com/f939971b9ed72f0803a41db3cba6ea0e/raw)](https://gyazo.com/f939971b9ed72f0803a41db3cba6ea0e)

**Comment by takahashi19** [comment]
本番環境だと↑でローカルだと下記が表示される
[![Screenshot from Gyazo](https://gyazo.com/8ca3702c95aba6b822403620fe864200/raw)](https://gyazo.com/8ca3702c95aba6b822403620fe864200)

**Comment by dh-megane** [comment]
今の遷移で良いんですかね...?
例外処理入れてNotFoundPageな気もしましたが、良いのかな...?

**Comment by takahashi19** [comment]
いやherokuの遷移なので修正致します。原因は特定できてないですがメソッドをfind_byにしたら動きました
