### ISSUE TITLE
user/show 存在しないユーザIDを指定した場合のエラー

### ISSUE THREAD

**Issue by dh-megane** [WEBsinjyuku/meister-hackers#337]
1. user/showを開く
![スクリーンショット 2019-03-10 10 13 16](https://user-images.githubusercontent.com/40923242/54079287-398a7a80-431d-11e9-9826-925f3329c7c0.png)
2. 存在しないユーザIDを指定して叩く。
https://meister-hackers.herokuapp.com/users/1
![スクリーンショット 2019-03-10 10 13 30](https://user-images.githubusercontent.com/40923242/54079289-40b18880-431d-11e9-88a3-c999f690489b.png)

**Comment by takahashi19** [comment]
ありがとうございます。
これは500ページにエラーが設定されており、500はページを用意してないので変遷先を404に替える必要があるかと思います。

**Comment by takahashi19** [comment]
エラー自体は500ということはpageを作る必要があるかもしれない
