### ISSUE TITLE
production環境の ユーザ編集画面が小さい

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#344]
[![Screenshot from Gyazo](https://gyazo.com/2abc8b827488da4f9dec60a9564477b4/raw)](https://gyazo.com/2abc8b827488da4f9dec60a9564477b4

* production環境のみ発生する
* 自由記述欄が小さすぎる
* フォームの横幅狭すぎる

**Comment by dh-megane** [comment]
```
config.webpack.production.js に
environment.loaders.get('vue').use[0].options.extractCSS = false
```
を追加しrails serverの再起動が必要かもしれません。

**Comment by dh-megane** [comment]
Production環境で表示が改善されたことを確認。クローズ。
