### ISSUE TITLE
開発者ブログ作成

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#351]
- Qiita
- Note
- Medium
- Original

**Comment by tsu-nera** [comment]
https://note.mu/menta

MENTAはNoteに飛ばしているな。これを採用したい。

**Comment by takahashi19** [comment]
SNS戦略について
ブログ：note
Gmail、Twitterアカウント取得を取得（来週まで）

ブログの内容
・月1回〜2回ブログを更新する。ブログ内容はこのプロダクトに少しでもあってれば良い（チーム開発の事や技術のことも含める）
・Meisterhackersの公式のブログまたはTwitter
・このブログが死んだ時サービスも終わる


#354

**Comment by tsu-nera** [comment]
https://twitter.com/MeisterHackers
https://note.mu/meister_hackers
