### ISSUE TITLE
2019/03/17 22:00 - ミーティング定例会 

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#354]
## 連絡事項

- [x] 議題の確認・司会、議事録の確認
- [x] 今週の実績
- [x] 来週の予定
- [x] 悩み・課題の共有
- [ ] その他連絡事
- [x] Demodayに関する確認（当日の参加の有無、名前の公開、画像の公開、動画の公開）(@takahashi19 )
- [x] DEMODAY発表資料レビュー(@takahashi19 ) #283 
- [x] ランディングページのレビュー(@tsu-nera )
- [x] SNS戦略について(@tsu-nera )
- [x] discourse導入の提案につきまして(@tsu-nera )

**Comment by tsu-nera** [comment]
## SNS戦略について

* 開発者ブログで情報発信をしたい
* Twitterで情報発信したい
* Slackコミュニティを盛り空けて情報発信をしたい。

皆さんのご意見をきく。

**Comment by takahashi19** [comment]
@tsu-nera 

土曜日でも良いですが21時以降か日曜日の21時以降
日曜日の方だと望ましいです。

**Comment by tsu-nera** [comment]
## ランディングページ

こちら、レビューしてもらいたいです。

https://github.com/WEBsinjyuku/meister-hackers/issues/117#issuecomment-472985825

**Comment by tsu-nera** [comment]
## Discourse導入のご提案

https://github.com/discourse/discourse

ホスティング料金がかかるが、世界でもっとも利用されている掲示板サービス。
オープンソースなら無料ホスティングできるかも。
https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

**Comment by dh-megane** [comment]
## 週報(dh-megane)

### 今週の実績
　バグ・機能改善対応（ #293, #346, #347, #348,  #360 ）

### 来週の予定
　バグ・機能改善対応（基本的に優先度2 / セキュリティ絡み強化 に着手する）

### 課題
　無

### その他連絡事項
　仕事の納品は無事完了したので、3月残りは落ち着くと思う...。
 （ヘルプで色々なプロジェクトに飛ばされるかも）

　４月以降は、自己啓発（ASP.NET MVC & Docker *Meister Hackersにも投稿予定）も
　やりたいので、その準備を週１-２日程度割きたいと思っています。

**Comment by tsu-nera** [comment]
## 週報(tsu-nera)

## 今週の実績

* LP

## 来週の予定

* はじめに
* About Us
* Discourse(できれば)

## 課題

流行性角結膜炎でした。普通に、インフル並の外出禁止なやばいやつでした。1週間引きこもり決定

さよなら〜〜〜

## その他連絡事項

**Comment by hiromoto-kazuya** [comment]
## 週報(ヒロモト)

### 今週の実績
なし、さーせん。。

### 来週の予定
マークダウン着手しますわ、、！

### 課題

### その他連絡事項

**Comment by shikky0331** [comment]
## 週報(shiki)

### 今週の実績
SNS share button SEO対策
### 来週の予定
就活！！！
### 課題

### その他連絡事項

**Comment by takahashi19** [comment]
## 週報(takahashi19)

### 今週の実績
・プレゼン資料半分完成
・プレゼン資料の構造
・Review適宜
・
### 来週の予定
・就活何社か受ける予定です。
・土曜日にDICがプレゼン練習&プレゼン内容のFBをDICサイドから受ける予定
・プレゼンの作成と発表
・Demoday用の提出資料の作成と取りまとめ（動作確認事項）
・Review随時
### 課題
・LPについては今日改めて、作った方がいいとの指摘を受ける
・
### その他連絡事項
・Demodayに関する事（議題にあげてる内容）

**Comment by takahashi19** [comment]
【議事録】
１Demodayに関する確認
　当日の参加⇨全員可
　名前の公開⇨全員可
　画像の公開⇨OK：レオさん
　　　　　　　条件付き：広瀬さん、しきさん、原田さん、ヒロモトさん
　動画公開⇨OK：レオさん、広瀬さん

 ２DEMODAY発表資料レビュー(@takahashi19 ) #283
　・issueみて文言がきになる所あれば随時コメントお願いします。
３ ランディングページのレビュー(@tsu-nera )
　・文言OK
　・LP画像大きいの一つ、小さいの二つを各自見つけたら用意する。
 ４SNS戦略について(@tsu-nera )
　・note、Gmail、Twitterアカウント取得を取得（来週まで）
 ５discourse導入の提案につきまして(@tsu-nera )
　・Demodayまでの導入はなし
６次回ミーティング予定
　・平日夜のもくもく会なし
　・24日（日曜日）22時〜ミーティング（オンライン）
