### ISSUE TITLE
サービスの悩み相談掲示板機能

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#358]
[![Screenshot from Gyazo](https://gyazo.com/e7be3efbcf7a7ea5f99f9b4ff059bc7f/raw)](https://gyazo.com/e7be3efbcf7a7ea5f99f9b4ff059bc7f)

個人開発に関する相談や、募集を投稿します。
「テスター募集」、「共同創業者を探しています」、「こんなアイデアはどうか？」など様々なフェーズに出てくる一人では解決できないような話題を自由に投稿することができるような場を目指しています。

**Comment by tsu-nera** [comment]
https://devtalk.jp/posts

**Comment by tsu-nera** [comment]
この機能はslackでいいかな？

**Comment by tsu-nera** [comment]
Discourseをものすごく使いたいです！！
https://github.com/discourse/discourse

オープンソースならば、無料でホスティングしてくれるそう。
https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

**Comment by tsu-nera** [comment]
こんなの
http://forum-titan-development-6349.nodechef.com/

**Comment by takahashi19** [comment]
Demoday以降導入するか再検討します
#354
