### ISSUE TITLE
2019/03/24 22:00 - ミーティング定例会 

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#367]
## 連絡事項

- [x] 議題の確認・司会、議事録の確認　予定1分
- [x] 今週の実績、来週の予定、悩み・課題の共有。各自　予定10分
- [x] その他連絡事・追加議題の確認
- [x] 次のミーティングの日程（31日22時〜で良いか）(@takahashi19)　予定5分
- [x]   プレゼン資料のReview　#283 (@takahashi19)　予定15分
- [x] 全体的な調整部分の相談（バグの部分）予定10分
- [ ] 追加議題　タスクもれと探索的レビュー

## 技術検討

- [x] v-cloakディレクティブをslimに書く方法の相談　#258 (@dh_megane)

**Comment by takahashi19** [comment]
## 週報(テンプレート)

### 今週の実績

### 来週の予定

### 課題

### その他連絡事項

**Comment by takahashi19** [comment]
## 週報（takahashi）

### 今週の実績
・プレゼン練習
・プレゼン資料の作成
### 来週の予定
・就活次第
・開発自体はもうないかと
・またDICでプレゼン練習あります
### 課題
・就活次第
・来週就職する可能性があります。
### その他連絡事項

**Comment by tsu-nera** [comment]
## 週報(tsu-nera)

## 今週の実績

* Noteアカウント作成
* Twitterアカウント作成

## 来週の予定

* なし

## 課題

* なし

## その他連絡事項

結膜炎は治りましたよ

**Comment by dh-megane** [comment]
## 週報（dh_megane）

### 今週の実績
アサインされた仕事が忙しく時間を確保できなかったです...。
- #258（仕掛）

### 来週の予定
- #355

### 課題
- #258
　v-cloakディレクティブをslimに書く方法が分からないので、対応する場合は
　単一ファイルコンポーネントに切り替えるべきか相談したいです。
　https://jp.vuejs.org/v2/api/#v-cloak

### その他連絡事項
３月末までは忙しい... m(._.)m

**Comment by takahashi19** [comment]
【追加議題】
・LPとマークダウンの締切。
　・29日の夜。30日締切
　・マークダウンをヒロモトさん確認。
　　→無理なら改行のみどうするか検討
　　　→無理な場合はmarkdownを入れない。
・LPの画像
　・マイスターハッカーズ。
　・TOP１枚　小さい２枚をワンセットで提出。

・募集の投稿
　・当日のみ全部募集開始にする。

・4月7日までのタスクもれ
　・最後にみる

・サイトの探索的レビュー
