### ISSUE TITLE
twiiter cardの画像

### ISSUE THREAD

**Issue by shikky0331** [WEBsinjyuku/meister-hackers#370]
![スクリーンショット 2019-03-19 22 59 53](https://user-images.githubusercontent.com/45489481/54611904-391b7d80-4a9b-11e9-935e-d36155dde78b.png)
twiiter cardは設定できていました！
まだ画像を設定してないので、使う画像は何がいいかあれば教えてください。

LPが完成したらそれとかでもいいんですかね？

**Comment by takahashi19** [comment]
https://ossteamhq.slack.com/files/UFAKCQTRV/FH9FGAFJT/____________________________2019-03-25_13.53.14.png

**Comment by takahashi19** [comment]
<img width="392" alt="スクリーンショット 2019-03-25 13 53 14" src="https://user-images.githubusercontent.com/40596064/54896084-c29cd680-4f05-11e9-9a29-818a0d8b706f.png">

**Comment by takahashi19** [comment]
これで！

**Comment by shikky0331** [comment]
githubのURLからだとtwiiter-cardのimageを取得できました
![スクリーンショット 2019-04-04 15 37 09](https://user-images.githubusercontent.com/45489481/55534589-cb549000-56ef-11e9-9562-e544f3e5715e.png)

サーバーから取得するように変更するのはデモデイの後でいいですかね？

**Comment by dh-megane** [comment]
デモデイの後で大丈夫だと思いますよー！

**Comment by tsu-nera** [comment]
なんだっけ？close
