### ISSUE TITLE
SNS share buttonのslackを押すとOAuth Error: Invalid client_id parameterが発生する

### ISSUE THREAD

**Issue by shikky0331** [WEBsinjyuku/meister-hackers#371]
タイトルのエラーが発生します。

**Comment by takahashi19** [comment]
少し調べたのですが
これってadd thisのSlackボタンを押すと立ち上がるのは自分のSlackという事でしょうか？

「OAuth Error: Invalid client_id parameter」

は認証のエラーじゃないかなと思うのでもしかしたら設定いるかもしれないですね。
こちらのadd thisの公式サイト？https://www.addthis.com/social-buttons/slack-button/でも同じようにSlackボタンで認証エラーになります。
[![Screenshot from Gyazo](https://gyazo.com/3a349e04d534aedcfb6195b31641d207/raw)](https://gyazo.com/3a349e04d534aedcfb6195b31641d207)

**Comment by takahashi19** [comment]
Slack消去したので閉じます
