### ISSUE TITLE
2019/03/31 22:00 - ミーティング定例会

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#379]
## 連絡事項

- [x] 議題の確認・司会、議事録の確認　予定1分
- [x] 今週の実績、来週の予定、悩み・課題の共有。各自　予定10分
- [x] その他連絡事・追加議題の確認
- [x] DEMODAY当日の流れについての連絡(@takahashi19 )→資料Slack（dic-demoday）
- [x] プレゼン資料のReview：15分(@tsu-nera  ) #283 
- [x] ユーザーテストのレビュー予定：15分(@takahashi19 ) #390 
- [ ] 4月7日までのタスク確認
　　・LP修正等（画像）
　　・コメントを消す→やらない
　　・addthisのSlack→（確認）
　　・404ページのお問い合わせ→

**Comment by takahashi19** [comment]
## 週報(テンプレート)

### 今週の実績

### 来週の予定

### 課題

### その他連絡事項

**Comment by shikky0331** [comment]
すみません！この日はミーティング参加できないです、、

**Comment by dh-megane** [comment]
## 週報(dh_megane)

### 今週の実績
#377, #378

### 来週の予定
データのクレンジング（コメントとか不要データの削除）

### 課題
なし

### その他連絡事項
来週も仕事が忙しい...が振って貰えれば対応します。

**Comment by takahashi19** [comment]
確認：資料の共有
　　　PCはDICの奴を使用したい
タスク：余裕があったら、noteの記事を投稿する。GitHubアカウント名、記事を投稿する。
LP修正：自分
