### ISSUE TITLE
ログインするとエラーしてなにもみえません

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#409]
[![Screenshot from Gyazo](https://gyazo.com/86030a1b37c2338d025eb5d806d8872c/raw)](https://gyazo.com/86030a1b37c2338d025eb5d806d8872c)

**Comment by dh-megane** [comment]
一覧画面のリポジトリ存在チェック処理の記述漏れが原因。
masterを直接更新して、正常に動作することを確認済みのため、クローズします。

**Comment by tsu-nera** [comment]
ありがとうございました。
