### ISSUE TITLE
【プロジェクト掲示板機能】新規投稿機能・編集機能

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#42]

**Comment by shikky0331** [comment]
プロジェクト投稿機能
・プロジェクト名
・プロジェクトの画像
・プロジェクトのURL(git hub)
・プロジェクトの概要（内容、開発期間、開発人数など）
・扱う言語 or フレームワークなど

プロジェクト編集機能
・投稿したプロジェクト内容の編集（上記）

**Comment by shikky0331** [comment]
githubでログインしてるとそういう機能もできるんですね！
試してみます！ありがとうございます！

**Comment by takaaa220** [comment]
そこまでのレスポンスがあるかはわからないですが，user_id さえあればapiからとってくることは可能だと思います！

**Comment by dh-megane** [comment]
>できればここ，githubログインしているので，その情報を使ってgithubの自分のレポジトリを
>自動で全件取得できるようにして，そこから選択できるようにするとユーザにとっていいかと．

自分のリポジトリが選択できるのは便利そうですね！

**Comment by tsu-nera** [comment]
[![Screenshot from Gyazo](https://gyazo.com/129c2bf41134f454400408d560210bd2/raw)](https://gyazo.com/129c2bf41134f454400408d560210bd2)

これができればやりたい。
https://www.codetriage.com/repos/new

**Comment by takaaa220** [comment]
まさにこれ

**Comment by shikky0331** [comment]
参考にします！ありがとうございます😊

**Comment by takaaa220** [comment]
## 概要
- プロジェクトの新規作成，編集機能
- このページにアクセスした時点で，作成者のレポジトリを自動取得し，選択できるようにする（とりあえず多すぎる場合は検討しない）
- マークダウンで概要を記入できるようにする
- マークダウンの確認を表示する（表示非表示を切り替えるボタンを入れる）
- 保存したタイトル，概要，URLはposts テーブルに入れる．

## 画面イメージ
<img width="340" alt="2019-01-25 12 59 13" src="https://user-images.githubusercontent.com/25857381/51724790-42432c00-20a2-11e9-8236-bc2f1a0727e5.png">

## 検討事項
- URLをDBに保存するのか，レポジトリ名をDBに保存するのか
https://api.github.com/repos/user_name/repo_name で情報は取得できる
  -> 個人的には，レポジドリ名で保存しておくと，検索できるので．（検索するときに，処理が必要）

- Post or Project テーブルのどちらに保存するのか
  -> 後々DBに保存することを見越して，Project テーブルを作成してそちらに入れたい．

- validationをどうするのか
  - url or repo-name はpresence: true
  - title に文字数制限がいるのか
  - description に文字数制限がいるのか，また，そもそも必須項目とするのか  

  -> 気持ち的に全部presence: trueでいいかな説

- レポジトリ名が変更される可能性があるので，それにはどう対応するのか

  -> とりあえず考えないことにしたい

**Comment by takahashi19** [comment]
迅速な対応ありがとうございます。なかなか高機能ですね。
ただ一点だけ気になったのですが、こちらの【募集概要】のところですが、【プロジェクト掲示板機能】一覧表示機能 #43の「簡易説明文」にはうまくDBから引っ張る事はできるのでしょうか？出来るのであれば全然問題ないかと思います！

**Comment by takaaa220** [comment]
こちら，レポジトリの簡易説明文で，それとは別のものとして検討していますが，違いますかね？

**Comment by takahashi19** [comment]
なるほどGitHubのDescriptionですね。#43の仕様をしっかりみてませんでした。

であればその形でいいかと思います。

**Comment by tsu-nera** [comment]
## レビュー指摘 tsu-nera

大枠はいいと思います。細かいところで少し気になることがあり、コメントします。

- GtiHubには、組織と個人のプロジェクトがあり、組織をどう選択させるかが悩みます。はじめは、開発対象から外すのもいいかも。Code Triageというサイトは、プルダウンの他にURL入力をさせるフォームを用意しているようでした。

- キャンセルボタンがあってもいいかも。

- gemの選定、プレビューがついてきているものもあると思います。けっこう入力フォームは種類があるかも。Rails6ではdefaultで入力エディタつくらしいですね。たぶん、JSでやることも考えて広く探してみるのがいいと思います。

**Comment by takaaa220** [comment]
- とりあえず，レポジトリを選択させるってことにします．
（多分個人であろうが組織であろうが情報は取ってこれると思うので）
- キャンセルというと...?
- プレビューのところは，jsですね~，そこだけvue のコンポーネントを作ってしまってもいいのかもしれないです．

**Comment by tsu-nera** [comment]
キャンセルはこれ。

[![Screenshot from Gyazo](https://gyazo.com/d1cd160c056f41571cf5cbd4413dcc06/raw)](https://gyazo.com/d1cd160c056f41571cf5cbd4413dcc06)

新規投稿はキャンセルなしで、編集はあるのが一般的？？一般的なほうに合わせたいです。

**Comment by takaaa220** [comment]
なーるほど

**Comment by dh-megane** [comment]
レビューしました。
## レビュー指摘（dh_megane）

>検討事項
>URLをDBに保存するのか，レポジトリ名をDBに保存するのか
>https://api.github.com/repos/user_name/repo_name で情報は取得できる
>-> 個人的には，レポジドリ名で保存しておくと，検索できるので．（検索するときに，処理が必要）

→　自分もリポジトリ名で良いと思います。
　（APIを叩いて、スター数や参加者数を表示することを考えるとリポジトリ名が便利かなと思います。）

**Comment by tsu-nera** [comment]
高橋さんにアサインしますので、よろしくお願いします。

**Comment by tsu-nera** [comment]
こちらはひろもとさんにアサインしました（書き忘れていた）

**Comment by tsu-nera** [comment]
* URL は ドメイン + リポジトリ名
* Post + Project は 1つ。
