### ISSUE TITLE
【プロジェクト掲示板機能】一覧表示機能

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#43]

**Comment by dh-megane** [comment]
# 機能仕様（プロジェクト掲示板機能）

## 検索機能
プロジェクトの検索を行う。

**①キーワード検索**

キーワード（プロジェクト名称？）で検索ができる。
検索処理は非同期通信（Ajax）にて行う。
検索結果は「○ results for ×××」というフォーマットで表示する。

**②絞込機能**

タグ（開発言語）で検索結果を絞り込むことができる。

## プロジェクト新規投稿画面への遷移機能
プロジェクト新規投稿画面へ遷移する。
ボタン「プロジェクト新規作成」を押下したタイミング。

## プロジェクト個別表示画面への遷移機能
プロジェクト個別表示画面へ遷移する。
リンク「VIEW PROJECT」を押下したタイミング。

## 画面イメージ
**全件検索**
![全件検索](https://user-images.githubusercontent.com/40923242/51423736-bcd5fc80-1c07-11e9-93fc-d7053df1f62c.png)

**キーワード検索**
![キーワード検索](https://user-images.githubusercontent.com/40923242/51423737-cc554580-1c07-11e9-922e-110fe1331354.png)

**Comment by takaaa220** [comment]
ページネーションが欲しいですね

**Comment by dh-megane** [comment]
ページネーションは最初検討したのですが、キーワード検索を非同期通信（リアルタイム）で行う
場合は難しいと思ってます。
Issue「既存サービス調査」で挙げて頂いたサービスは一通り画面を確認したのですが、
同期処理で検索　　⇨ ページネーション有り
非同期処理で検索　⇨ ページ下部まで移動したら追加で読み込み（LOAD MORE)を行う
という作りが多かったです。

下スクロールで画面下部まで移動した場合は「PAGE TOP」ボタンで上部に戻ってもらう方式を
考えています。ページ読み込みに時間がかかる場合は、対策が必要です。

**Comment by takaaa220** [comment]
なるほどー
追加でローディングを考えてるなら、ページ読み込みにそこまで時間かからないかとー

段階的に変えていくとかいいかもしれないですね！
まずは同期でやってくとか！

**Comment by dh-megane** [comment]
# 機能仕様（プロジェクト掲示板機能）機能見直し版
サービスに登録されているプロジェクトの一覧をリスト形式で表示。1行に表示する明細数は1つ。

<img width="419" alt="default" src="https://user-images.githubusercontent.com/40923242/51567611-fa25dd00-1eda-11e9-9a06-826fa6ea0e60.png">

【リスト内容の項目説明】＊**太字はAPIで取得する情報**
- キーワード（GitHubで設定したリポジトリ名称：**name**）
- ロゴ（サービス側でプロジェクト登録時に設定したもの）
- タグ（GitHubで設定した言語：**language**とGitHubで設定したtopics：**topics**)
- 簡易説明文（GitHubで設定した説明文：**description**)
- ★Star（GitHubでのStar数：**stargazers_count**）
- 👥contributors（GitHubでのcontributors数：**contributors**を集計）＊Collaboratorsに変更するかも？
- リンク
  - 他人が作成したプロジェクトの場合：「VIEW PROJECT」＊プロジェクト個別表示画面
  - 自分が作成したプロジェクトの場合：「EDIT PROJECT」＊プロジェクト投稿画面へ遷移）

## 検索機能
変更前：キーワード検索と絞込機能を実装する。
変更後：**１次リリースでは検索機能は実装しない。**
＊最新情報を表示したい場合は、リロードする。

## プロジェクト投稿画面へ遷移（新規モード）
「プロジェクト新規登録」ボタンを押下すると、プロジェクト投稿画面へ遷移する。
＊プロジェクト投稿画面は新規モードで開くこと。

## プロジェクト投稿画面へ遷移（編集モード）
「EDIT PROJECT」リンクを押下すると、プロジェクト投稿画面へ遷移する。
＊プロジェクト投稿画面は編集モードで開くこと。

## プロジェクト個別表示画面へ遷移
「VIEW PROJECT」リンクをプロジェクト個別表示画面へ遷移する。

## 余裕があれば機能追加したいもの
- 1行に2明細を表示する（⇨ ウインドウ幅が狭くなった場合は1明細で表示する）
- キーワード検索

**Comment by dh-megane** [comment]
参考にしているデザインは「Google Open Souce」というサービスです。

<img width="931" alt="default" src="https://user-images.githubusercontent.com/40923242/51568840-09f2f080-1ede-11e9-8af7-360acbbcb74d.png">

**Comment by tsu-nera** [comment]
## レビュー指摘 tsu-nera

たんへんよいと思いました。

### 全体

指摘1)
ロゴは必要ですかね？？GitHubにロゴの概念もないですし。
画像アップロード機能は簡単にできればいいのですが、後回しでもいい気がしますがどうでしょうか？

指摘2)
私の認識とみんなの認識がずれているかもしれないので、みなさんここは見てほしいです。
私の認識では、掲示板投稿の内容とGitHubの情報の２つを投稿内容として管理するのかと考えていました。

掲示板投稿
- タイトル
- 本文

GitHub情報
- リポジトリ名
- 説明文
- その他...

なので、プロジェクト一覧のタイトルは "参加者募集中!!!" のようなキャッチフレーズが入るのだと考えていました。
ここについて、全員の認識はあっているでしょうか？？


### その他

機能仕様ではないのですが、このあとは内部設計をせずに実装にいくと思うので、内部設計についても気になることを書きます。

指摘3)
GitHubからの情報をどう取得するかが気になります。
Keywords, Stars、Contributer、descriptionが変動するため、これは表示のたびに取得する必要があると思います。

はじめ、Rails Cacheをつかってキャッシュで情報をもって、APIを表示するたびに叩けばいいと思ったのですが、
ソートや検索機能を考えるとDBに情報がないとそれが実現できないことに気づきました。

ほかのサービスとか、このへんどう解決しているのですかね？？

今すぐよい代替案も思いつかなくて、とりあえず問題提起だけしておきます。

**Comment by dh-megane** [comment]
@tsu-nera 
**指摘１) 画像ロゴについて** 
確かに...ロゴは要らないですね。画像の大きさ等のチェックも大変そうですし、
何よりロゴがないからという理由でプロジェクト新規投稿を躊躇うユーザが発生しそう。

**指摘２)**
>なので、プロジェクト一覧のタイトルは "参加者募集中!!!" のようなキャッチフレーズが入る～

今の画面レイアウトだと、
**「メンバー募集してます（一緒にチーム活動・OSS活動を始めようぜ！）」** ではなく
**「OSSの一覧を表示したもの」** という印象を受けるということでしょうか？
それはありますね...。リポジトリ名ではなく、キャッチフレーズにすべきですね。

@tsu-nera さんの認識で合ってます。自分の認識が誤ってた感じです。

＊Teamlancerの画面レイアウト
<img width="780" alt="2" src="https://user-images.githubusercontent.com/40923242/51619315-618f6b80-1f73-11e9-8c8e-3d62dfc2dca1.png">

**指摘3)**
#65 で回答します。

@takaaa220 
**１．**
指摘ありがとうございます。
description や topic が未設定の場合の画面レイアウトも検討・作成します。

**２．**
自分もロゴは不要という意見になりました。
 @LeonardoMatusaki さんの #44 、スプレッドシート「**GITHUBプロダクトDB設計**」もロゴを
使用する想定になっているので、指摘・見直しを依頼します。 

**３．**
@takaaa220 さんの指摘を採用した案のほうが使い勝手が良いと自分も思うので、実装してみます。
＊「Google Open Souce」もVIEW PROJECTだけでなく全体もリンクになっているのでそれを参考にしてみます。

**Comment by tsu-nera** [comment]
これは完了した。閉じる。
