### ISSUE TITLE
【プロジェクト掲示板機能】個別表示機能

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#44]

**Comment by LeonardoMatusaki** [comment]
# 機能仕様（プロジェクト掲示板機能）

## 機能
プロジェクト単体の表示をする

**①プロジェクトの表示**
プロジェクトの説明の表示
プロジェクトの参加者の表示

**②チャット機能**
コンパスやqiitaのように公開形式のチャット機能
（公開にする理由：同じ質問をさせないため（メッセージコストをあげないため）


## トップページ画面への遷移機能
ヘッダーでトップページ画面への遷移ボタンをつける

**Comment by LeonardoMatusaki** [comment]
## 画面イメージ
![oss-show_project](https://user-images.githubusercontent.com/39451570/51438107-ff243a00-1cea-11e9-938a-f453146dcdc1.png)

**Comment by LeonardoMatusaki** [comment]
### 補足
・カテゴリーなどがあれば、説明文とタイトルの間に表示
・チャット機能ではなくコメント投稿&閲覧機能（これはチャット機能がない場合&自分の作業時間が足りた場合のみにつけるイメージ）

**Comment by takaaa220** [comment]
何点かコメントさせていただきます．

githubからとってくる情報はどんな感じで表示しますか？
そもそも表示しない感じでしょうか？

参加ボタン（現状は起案者にメールを行くようにするって感じでしたよね）
をどこにどんな感じで入れます？
また，メールを送るとしたら，レオさんが実装されますか？
それともそれは別のIssueとしてここでは扱わない感じですかね？

**Comment by LeonardoMatusaki** [comment]
コメントありがとうございます。

下、回答です。
・参加ボタンに関しては、タイトルの右に配置します。
・メール送信機能は、基本的に自分で作りますが（対応が難しいようであれば、早めに相談します）
・githubからの取ってくる情報は（星の数、コントリビューターの数、言語、タグ：表示位置は基本的にタイトルと説明文の間に表示します（上の補足で書いたカテゴリーのことです。））

**Comment by tsu-nera** [comment]
## レビュー指摘 tsu-nera

- GitHubからとってくる情報は　https://github.com/WEBsinjyuku/github-open-products/issues/44#issuecomment-455852566　に追記をお願いします。

- メール送信機能(ActionMailerですが）、別issue にしたいです。ここは、チャット機能との棲み分けも議論が必要です。チケットは切っておきます。

- GitHubを模倣するといい気がしていて、左のサイドバーにGitHub情報を、メインに記事をもってくるのがいい気がしますがどうでしょう？ここはデザインなので、センスかもしれませんが。

[![Screenshot from Gyazo](https://gyazo.com/73e3e808d84253fc226ad3525ece8a39/raw)](https://gyazo.com/73e3e808d84253fc226ad3525ece8a39)

- slackで議論中ですが、編集ボタンと削除ボタンをいれる可能性があります。

**Comment by LeonardoMatusaki** [comment]
レビューありがとうございます。

githubのデザインでもいいのかなーと思いますけど、メインは人じゃなくてプロジェクトなのかなーと思い起案者・参加者を右と考えてます。
また、起案者・参加者の情報をgithubほど詳細に表示しなくてもいいのかなーとも思ってます。

**Comment by tsu-nera** [comment]
ちょっと時間が経ってしまいましたが、
https://github.com/WEBsinjyuku/github-open-products/issues/44#issuecomment-455852566

をアップデートして、再レビュー依頼をかけてくれますか？

平田さんがmasterにベースをマージしてくれたので、それをもとに勉強がてら平行してつくりはじめてもいいです。

**Comment by takahashi19** [comment]
https://ossteamhq.slack.com/files/UFCCZH0DA/FGA5EPRNX/localhost_3000_posts_show.png

**Comment by tsu-nera** [comment]
* サイズは仮

**Comment by LeonardoMatusaki** [comment]
@takahashi19 
このイシューは閉じてOKですか？

**Comment by takahashi19** [comment]
okです閉じます
