### ISSUE TITLE
CircleCIの導入

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#54]

**Comment by tsu-nera** [comment]
RSpecの実行。
branch自動削除の仕組みもいれたい。

**Comment by tsu-nera** [comment]
深夜の自動マージもできればしたい。

**Comment by takahashi19** [comment]
お手数おかけします。

**Comment by tsu-nera** [comment]
今日の勉強会でのお話。docker-composeを動かす専用のdockerをつくって、DockerHubにあげて、それをCircleCIでつかう。これによって、サイズも小さくなるし、スピードもはやくなるとアドバイスをもらう。

自前のDockerをHubにあげる発想はなかったな。これは時間をとって挑戦してみたいな。

**Comment by tsu-nera** [comment]
すみません、やれませんが、優先度も高くないため、保留にさせてください。

やろうと思えばできるのですか、私が設定すると、一回のサイクルで５分かかるので、本当にいいんだっけと思っています。

**Comment by tsu-nera** [comment]
テストかかないので、導入断念。
