### ISSUE TITLE
READMEの編集

### ISSUE THREAD

**Issue by tsu-nera** [WEBsinjyuku/meister-hackers#75]
だれかちゃんとかいて。
できれば、オープンソースの一般的なベストプラクティスに従って書く。

**Comment by tsu-nera** [comment]
わたしが書きますね。

**Comment by tsu-nera** [comment]
やっぱり高橋さんと相談します。アサインも高橋さんを加えました。

**Comment by takahashi19** [comment]
READMEは @tsu-nera さん記載で良いですよ。
もし下書きという事であれば明日もくもく会の際に実際にLT資料をお見せ致します。

**Comment by takahashi19** [comment]
プレゼン資料作成と同時に開始します

**Comment by takahashi19** [comment]
demoday用のは記入終了

**Comment by tsu-nera** [comment]
できればこれにしたがいたいです。
[良い README\.md を書くためのテンプレート（翻訳） \- Qiita](https://qiita.com/KamataRyo/items/466255fc33da12274c72)
