### ISSUE TITLE
【ユーザー認証機能】navbar作成

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#96]
【navbar仕様】

- 【GitHubログイン】【ログアウト】ボタンを右辺に設置

- navbar左辺にMeister Hackersの文字もしくはロゴ。クリックした際はtopページ【プロジェクト掲示板一覧表示】 に飛ぶ

- レスポンシブに動く

- navbar左辺にユーザ名かユーザーアイコンの表示（user nameで調整。余裕あればアイコンにします）

- navbarの色は黒か緑（ここご意見ほしいですー。）

イメージは下にcommentします。

**Comment by takahashi19** [comment]
未完成につきオープン
ログイン横に名前とナビバー左側にはロゴ入れる
[![Screenshot from Gyazo](https://gyazo.com/3ba1124f1195edfa743328f269edb7e3/raw)](https://gyazo.com/3ba1124f1195edfa743328f269edb7e3)

**Comment by takahashi19** [comment]
[![Screenshot from Gyazo](https://gyazo.com/519ca62a07f677ee3125845c0b7d9b75/raw)](https://gyazo.com/519ca62a07f677ee3125845c0b7d9b75)
[![Screenshot from Gyazo](https://gyazo.com/8c821edd449d70fb20604c853ea7c4e0/raw)](https://gyazo.com/8c821edd449d70fb20604c853ea7c4e0)
[![Screenshot from Gyazo](https://gyazo.com/5465d91ccc204a2334b18f0fcc194551/raw)](https://gyazo.com/5465d91ccc204a2334b18f0fcc194551)

**Comment by tsu-nera** [comment]
## レビュー指摘 tsu-nera

* サインイン・サインアウト or ログイン・ログアウトのどちらかに統一したいです。
* このサイトは日本人をターゲットにしているため、ボタン名なども日本語に統一したいです。
* meisterp-hackersの **Meister Hackers** にしたいです。
* ユーザアイコンを表示するためには、ユーザアイコンのURLはUserテーブルに保存する必要があり。
* NavBarの色は緑。なぜなら、ドイツなので。

**Comment by takahashi19** [comment]
Reviewありがとうございます。
> サインイン・サインアウト or ログイン・ログアウトのどちらかに統一したいです。
このサイトは日本人をターゲットにしているため、ボタン名なども日本語に統一したいです。

ログインログアウトにします。【GitHubログイン】【ログアウト】の二つで

>meisterp-hackersの **Meister Hackers** にしたいです。

訂正しました！

> ユーザアイコンを表示するためには、ユーザアイコンのURLはUserテーブルに保存する必要があり。

ここは出来るかわからないのでnameで先に挑戦します。

> NavBarの色は緑。なぜなら、ドイツなので。

barは緑。ボタンの色は黒にしようかと思います

**Comment by dh-megane** [comment]
自分はOKです。気になるところありません。
- navbarの色は黒か緑（ここご意見ほしいですー。）
他の方も意見されている通り、緑で良いです！
黒だとGitHubで同じでGitHubへのリンクを貼った場合に一目で識別できないかもですし。

**Comment by hiromoto-kazuya** [comment]
私も気になる所、ありませんでした！

**Comment by tsu-nera** [comment]
新規投稿ボタンをつける

**Comment by takahashi19** [comment]
Reviewありがとうございます。仕様通りに一旦作成しました（ロゴ以外）。デザインの修正が入るまで一旦閉じます
