### ISSUE TITLE
LT大会イベントの設置

### ISSUE THREAD

**Issue by takahashi19** [WEBsinjyuku/meister-hackers#98]
## 予定
- 開催予定は3月1日　渋谷夜19時〜
- 次は休日昼＠西新宿で検討中
- 告知はConnpass利用
- 告知は順次

**Comment by takahashi19** [comment]
https://websinjyuku.connpass.com/event/119485/preview/

**Comment by tsu-nera** [comment]
対面で会って話をきいて、趣旨は理解しましたし、応援しますよ〜。

**Comment by dh-megane** [comment]
イベント主催？して告知する感じですかね、良いねですね！
下記URLについて自分はまだアクセス権がないのか404エラーが返ってきます。
https://websinjyuku.connpass.com/event/119485/preview/
<img width="1128" alt="3" src="https://user-images.githubusercontent.com/40923242/52219741-95a64d00-28e0-11e9-8700-69794bf1b3cf.png">

**Comment by takahashi19** [comment]
## 概要
オープンソースでプロダクトを作ったり発表するためのイベントです。LTだけでなくもくもく会としても活用ください<br>
未経験者で、ポートフォリオを一人で作るのに苦戦している！<br>
チーム開発の経験がしたい！<br>
プログラミング仲間がほしい！<br>
他の人と技術交換したい！<br>
GitHubのより実践的な使い方を知りたい！<br>
他の人のプロダクトやLTをただ聞いてみたい人<br>
単純にもくもくだけしたい！<br>
など、どんな目的でもOKです<br>
途中参加、途中退場OKです。言語もRuby,Java,php,Python,Kotlin,C#,JavaScriptなんでも大丈夫です<br>
<br>

## 参加対象者
エンジニア<br>
エンジニアになりたい人<br>
サービスを作ってみたい人<br>
Webデザインしてみたい人<br>
プログラミングをしたい人<br>
初心者　学生・非エンジニア職の方参加可能<br>
ベテランの方も大歓迎<br>

##LT枠の参加者

①プロダクトメンバー募集のLT枠<br>
　・今から作り始めます/メンバーがいればやります/やってるけどメンバー追加募集の方が対象<br>
②プロダクトを発表したいLT枠（5分）<br>
　・プロダクトは完成していて発表したい/生のフィードバックが欲しい方が対象<br>
③ノージャンルのLT枠(5分)<br>
　・好きな事を話す5分枠。プログラミング勉強法、筋トレ、SNS、ライティングなんでもOK<br>
※参加共通条件<br>
・プロダクトはオープソースである事！（プライベートリポジトリのプロダクト作成や発表はご遠慮ください）<br>
・LT枠参加者は前日までにSlack（メンバー募集の方は掲示板にテンプレの内容を書き込んで教えてください）というチャットツールに参加の上テーマを送ってください。<br>
・Googleスライドで作成する事を推奨します<br>
・順番は基本的にこちらで決めます。メンバー募集/プロダクト発表/ノージャンル全体でLT枠7の予定です。登壇者確定次第連絡します（基本先着）<br>

##持ち物・用意するもの
githubアカウント（推奨）<br>

##当日のスケジュール内容
19:00　会場提供のスポンサー枠<br>
19:10　主催者の挨拶<br>
19:15　LT枠①テーマ：<br>
19:22　LT枠②テーマ：<br>
19:29　LT枠③テーマ：<br>
19:36　LT枠④テーマ：<br>
19:43　LT枠⑤テーマ：<br>
19:50　LT枠⑥テーマ：<br>
19:57　LT枠⑦テーマ：<br>
20:00　テーブル毎に自己紹介後、もくもく会開始<br>
22:00　撤収<br>

##チーム開発専用募集の掲示板
募集される方はこちらに投稿お願いします<br>
https://github-open-products.herokuapp.com/<br>
##場所・スポンサー(仮)

https://www.doorkeeper.jp/%E4%BC%9A%E5%A0%B4/diveintocode　<br>
##連絡手段
質問や何かあればSlackにてご連絡をお願いします<br>


##注意事項
会場にWifiはありますが電源はありませんのでご注意ください<br>
当日テーブルの移動や席の移動などをお願いする事がありますがその点はご了承ください<br>

**Comment by takahashi19** [comment]
# Connpassページ
## プロダクトを作りたい/発表したいエンジニアの勉強会&もくもく会@渋谷（タイトル）

参加者枠：20人
プロダクトメンバー募集のLT枠（5分）：3人
プロダクトを発表したいLT枠（5分）：3人
内容問わずのLT枠（5分）：1人

**Comment by takahashi19** [comment]
先方に日程打診済み
Compassグループページを新設しメンバー全員が見れるように設定

**Comment by takahashi19** [comment]
preview作成済み。先方にOKもらいました。公開前の画面あるのでインデントの修正や誤字脱字のチェックをしていただければと思います。掲示板への誘導は間に合うか微妙なので外しました（うまくいけば3月中旬に西新宿でLT会開けるのでその時にします）下記のReviewお願いします
https://connpass.com/event/119983/edit/

**Comment by tsu-nera** [comment]
2点修正しました。

* php > PHP
* github > GitHub

<br> が気になりますが、修正はしていません。

**Comment by dh-megane** [comment]
@takahashi19 
自分もチェックしました。特に気なる箇所はありませんでした。
ありがとうございます！

**Comment by takahashi19** [comment]
ありがとうございます！

**Comment by tsu-nera** [comment]
本日公開した。

これはもう済かな？？大丈夫そうなら、とじちゃってください。
